// src/lib/bestiario.js

export const bestiario = [
  // --- CRIATURAS DE SANGUE ---
  {
    id: "aberracao_de_carne",
    nome: "Aberração de Carne",
    elemento: "Sangue",
    vd: 40,
    tipo: "Criatura - Grande",
    presenca: "Perturbadora (DT 15 • 3d6 mental • NEX 30%+ é imune)",
    foto: "/assets/bestiario/aberracao.webp",
    sentidos: "Percepção +5, Percepção às cegas",
    iniciativa: "2d20",
    defesa: 19,
    fortitude: "3d20+10",
    reflexos: "2d20",
    vontade: "1d20",
    pv_max: 70,
    pv_atual: 70,
    machucado: 35,
    resistencias: "Balístico, impacto, perfuração 5, Sangue 10",
    vulnerabilidades: "Morte",
    atributos: { agi: 1, for: 3, int: 0, pre: 1, vig: 3 },
    deslocamento: "9m | 6q",
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (Corpo a corpo x2). Teste 3d20+10 | Dano 2d6+6 impacto.",
      },
      {
        nome: "Agarrão (Reação)",
        descricao: "Se acertar um ataque de pancada, pode tentar agarrar (teste 3d20+12). Mantém até 2 personagens.",
      },
      {
        nome: "Abocanhar (Movimento)",
        descricao: "Leva até 2 agarrados para a boca. Agarrados sofrem 3d6 perfuração no início do turno da criatura (Fort DT 15 metade). Atletismo DT 20 para escapar.",
      },
    ],
  },
  {
    id: "aniquilacao",
    nome: "Aniquilação",
    elemento: "Sangue",
    vd: 380,
    tipo: "Criatura Colossal",
    presenca: "Perturbadora (DT 45 • 9d8 mental)",
    foto: "/assets/bestiario/Aniquilacao.webp",
    sentidos: "Percepção 40+20, Percepção às cegas",
    iniciativa: "40+20",
    defesa: 58,
    fortitude: "50+30",
    reflexos: "40+25",
    vontade: "40+20",
    pv_max: 1200,
    pv_atual: 1200,
    machucado: 600,
    resistencias: "Dano 50",
    vulnerabilidades: "Morte",
    atributos: { agi: 4, for: 5, int: 3, pre: 4, vig: 5 },
    deslocamento: "15m | 10q",
    habilidades: [
      "ENIGMA DE MEDO: Desconhecido. Quando resolvido, perde resistência a dano e Tempestade de Espinhos.",
      "INSTINTO ANIQUILADOR: (Reação) Se alvo se move > 3m, Tentáculos Espinhentos.",
      "DECEPAR MÁSCARA: (O Diabo) A intensidade dos sentimentos do Diabo é a única coisa capaz de resolver o Enigma de Medo da Máscara do Desespero.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS (C.C. x2) Teste 50+40 | Dano 4d10+30 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "TENTÁCULOS ESPINHENTOS (C.C. x2) Teste 50+40 | Dano 2d12+30 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "DISPARO DE ESPINHOS (Distância x3 - Médio) Teste 40+40 | Dano 2d10+20 Sangue.",
      },
      {
        nome: "Agarrão (Reação)",
        descricao: "Se acertar Tentáculos Espinhentos, pode agarrar (teste 50+50). Mantém até 4 alvos.",
      },
      {
        nome: "APERTAR E DESTRUIR (Livre)",
        descricao: "Início do turno: Alvos agarrados sofrem 40 de dano de Sangue.",
      },
      {
        nome: "BATER AS ASAS (Movimento)",
        descricao: "Todos em alcance longo sofrem 8d6 Mental, empurrados 6m, Atordoado 1 rodada (Fort DT 40 reduz à metade e evita).",
      },
      {
        nome: "ESTRANGULAMENTO FINAL (Movimento)",
        descricao: "Todos adjacentes ao deslocamento de 15m ficam Agarrados e Asfixiados (Reflexos DT 30 evita).",
      },
      {
        nome: "TEMPESTADE DE ESPINHOS (Completa)",
        descricao: "1x/cena. Todos em alcance médio sofrem 20d6+20 Sangue (Reflexos DT 40 reduz à metade).",
      },
    ],
  },
  {
    id: "carente",
    nome: "Carente",
    elemento: "Sangue",
    vd: 300,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 35 • 7d8 mental • NEX 90%+ é imune)",
    foto: "/assets/bestiario/Carente.webp",
    sentidos: "Percepção 30+10, Percepção às cegas",
    iniciativa: "40+15",
    defesa: 40,
    fortitude: "40+25",
    reflexos: "40+25",
    vontade: "30+15",
    pv_max: 700,
    pv_atual: 700,
    machucado: 350,
    resistencias: "Balístico, impacto, perfuração e Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 4, for: 4, int: 2, pre: 3, vig: 4 },
    deslocamento: "12m | 8q",
    habilidades: [
      "REGENERAÇÃO DE SANGUE: Cura Acelerada 20. Desativa se inconsciente ou dano de Energia.",
      "CARÊNCIA: Seres envolvidos em gestação: +2O em ataques contra o Carente, e +O em ataques do Carente contra esse ser.",
      "FORMA INFANTIL: Não abre a primeira porta. Pode se retrair para passar em espaços pequenos.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS DE SANGUE (C.C. x2) Teste 40+35 | Dano 2d8+20 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "FERRÃO DE SANGUE (C.C.) Teste 40+35 | Dano 2d12+20 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "TENTÁCULO (C.C.) Teste 40+35 | Dano 2d8+20 Sangue.",
      },
      {
        nome: "SUGADA MORTAL (Livre)",
        descricao: "Acerto Ferrão: alvo fica debilitado e enjoado (Fort DT 35 evita).",
      },
      {
        nome: "RASTEIRA DE TENTÁCULO (Reação)",
        descricao: "1x/rodada adjacente a 2+ seres. Acerto Tentáculo: vítima fica caída e empurrada 6m.",
      },
      {
        nome: "VOCÊ É MINHA MAMÃE? (Movimento)",
        descricao: "Abraça ser adjacente, que fica paralisado (Reflexos DT 25 evita). Sofre dano de Energia, solta.",
      },
    ],
  },
  {
    id: "dama_de_sangue",
    nome: "Dama de Sangue",
    elemento: "Sangue",
    vd: 60,
    tipo: "Criatura Enorme",
    presenca: "Perturbadora (DT 20 • 3d6 mental • NEX 35%+ é imune)",
    foto: "/assets/bestiario/Dama de Sangue.webp",
    sentidos: "Percepção 20+10, Percepção às cegas",
    iniciativa: "2d20",
    defesa: 20,
    fortitude: "20+10",
    reflexos: "20+5",
    vontade: "2d20",
    pv_max: 105,
    pv_atual: 105,
    machucado: 52,
    resistencias: "Balístico, impacto e perfuração 10, Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 2, for: 3, int: 1, pre: 2, vig: 2 },
    deslocamento: "12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Destruir as 7 flores por fraquezas elementais/físicas.",
      "CONSUMIR: Gana uma das 7 habilidades por consumir 1 corpo (máx 7 corpos).",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "TENTÁCULO (C.C. x2) Teste 3d20+10 | Dano 2d6+5 impacto.",
      },
      {
        nome: "ARREMESSAR (Movimento - Flor Rosa)",
        descricao: "Arremessa alvo (alcance curto): Dano 2d6 impacto, caído (Reflexos DT 15 evita).",
      },
      {
        nome: "CHUVA DE ÁCIDO (Movimento - Flor Vermelha)",
        descricao: "Todos em alcance curto sofrem 4d4 Químico (Fort DT 15 reduz à metade).",
      },
      {
        nome: "ESPINHOS (Movimento - Flor Amarela)",
        descricao: "3 alvos em alcance médio sofrem 2d8 perfuração (Reflexos DT 15 reduz à metade).",
      },
      {
        nome: "GRITO DEVASTADOR (Movimento - Flor Roxa)",
        descricao: "Todos em alcance curto ficam confusos (Vontade DT 15 evita).",
      },
      {
        nome: "MIASMA FÉTIDO (Padrão - Flor Azul)",
        descricao: "Todos em alcance curto ficam enjoados 1d4+1 rodadas (Fort DT 15 reduz à 1 rodada).",
      },
      {
        nome: "PRISÃO DE TENTÁCULOS (Padrão - Flor Verde)",
        descricao: "Alvo em alcance curto agarrado até que tentáculos (20 PV) sejam destruídos. (Defesa -5)",
      },
      {
        nome: "VISÃO MACABRA (Movimento - Flor Laranja)",
        descricao: "Todos em alcance médio sofrem 1d6 Mental (Vontade DT 15 reduz à metade).",
      },
    ],
  },
  {
    id: "enpap_x",
    nome: "Enpap-X",
    elemento: "Sangue",
    vd: 180,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 25 • 6d6 mental • NEX 60%+ é imune)",
    foto: "/assets/bestiario/Enpap-X.webp",
    sentidos: "Percepção 20+10, Percepção às cegas",
    iniciativa: "20+10",
    defesa: 36,
    fortitude: "30+15",
    reflexos: "20+15",
    vontade: "20+10",
    pv_max: 360,
    pv_atual: 360,
    machucado: 180,
    resistencias: "Balístico, impacto e perfuração 10, Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 2, for: 4, int: 1, pre: 2, vig: 3 },
    deslocamento: "12m | 8q",
    habilidades: [
      "TRANSFORMAÇÃO: Começa como Existido (p. 240). Ao ser reduzido a 0 PV, transforma-se nesta forma, recuperando 360 PV.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "SOCÃO (C.C. x4) Teste 40+20 | Dano 2d10+10 impacto.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "CORRENTES (Distância x3 - Curto) Teste 20d20+15 | Dano 2d8+10 impacto.",
      },
      {
        nome: "ACORRENTAR (Livre)",
        descricao: "Acerto Correntes (Médio ou menor): agarra à distância (Teste 20d20+17). Início do turno: Estrangula 4d6 impacto.",
      },
      {
        nome: "FORMA DESENCADEADA (Reação)",
        descricao: "Acerto Crítico Socão/Correntes: derruba ou empurra 3m.",
      },
      {
        nome: "CRESCER (Reação)",
        descricao: "Acerto Socão: +1d6 cumulativo no dano do próximo socão no turno.",
      },
      {
        nome: "MARCAS DO TERROR (Movimento)",
        descricao: "Todos em alcance curto sofrem 4d6 Mental (Vontade DT 25 reduz à metade).",
      },
    ],
  },
  {
    id: "kerberos",
    nome: "Kerberos",
    elemento: "Sangue",
    vd: 340,
    tipo: "Criatura Enorme",
    presenca: "Perturbadora (DT 35 • 10d6 mental • NEX 99%+ é imune)",
    foto: "/assets/bestiario/Kerberos.webp",
    sentidos: "Percepção 30+20, Percepção às cegas",
    iniciativa: "40+15",
    defesa: 46,
    fortitude: "50+25",
    reflexos: "40+20",
    vontade: "30+15",
    pv_max: 1150,
    pv_atual: 1150,
    machucado: 575,
    resistencias: "Balístico, impacto, perfuração e Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 4, for: 5, int: 0, pre: 4, vig: 5 },
    deslocamento: "18m | 12q",
    habilidades: [
      "ATAQUE FLEXÍVEL: Pode executar 4 ataques por rodada (C.C. e Distância), mas o mesmo ataque no máx 3x/rodada.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA (C.C.) Teste 50+40 | Dano 4d12+30 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "DISPARO DE ESPINHOS (Distância - Médio) Teste 40+35 | Dano 4d8+20 Sangue.",
      },
      {
        nome: "DEVORAR (Livre)",
        descricao: "1x/cena. Reduz PV a 0: mata e recupera PV (Fort DT 40 evita).",
      },
      {
        nome: "DERRUBAR E DEVORAR (Completa)",
        descricao: "Manobra Derrubar (Teste 50+45). Sucesso: 3x Mordida, Dano 4d12+40.",
      },
    ],
  },
  {
    id: "minotauro",
    nome: "Minotauro",
    elemento: "Sangue",
    vd: 280,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 35 • 8d6 mental • NEX 80%+ é imune)",
    foto: "/assets/bestiario/Minotauro.webp",
    sentidos: "Percepção 30+20, Percepção às cegas",
    iniciativa: "40+15",
    defesa: 44,
    fortitude: "50+20",
    reflexos: "40+15",
    vontade: "30+10",
    pv_max: 750,
    pv_atual: 750,
    machucado: 375,
    resistencias: "Balístico, impacto, perfuração e Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 4, for: 5, int: 1, pre: 3, vig: 5 },
    deslocamento: "12m | 8q",
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "CHIFRES (C.C.) Teste 50+30 | Dano 6d12+20 perfuração.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "MACHADO (C.C. x2) Teste 50+32 | Dano 4d12+20 corte.",
      },
      {
        nome: "CRAVAR CHIFRES (Livre)",
        descricao: "Investida Chifres: alvo agarrado. Sofre 4d12+20 Sangue por turno.",
      },
    ],
  },
  {
    id: "tita_de_sangue",
    nome: "Titã de Sangue",
    elemento: "Sangue",
    vd: 220,
    tipo: "Criatura Colossal",
    presenca: "Perturbadora (DT 30 • 7d6 mental • NEX 70%+ é imune)",
    foto: "/assets/bestiario/Titã de Sangue.webp",
    sentidos: "Percepção +15, Percepção às cegas",
    iniciativa: "20+10",
    defesa: 35,
    fortitude: "40+15",
    reflexos: "20+10",
    vontade: "1d20+10",
    pv_max: 550,
    pv_atual: 550,
    machucado: 275,
    resistencias: "Balístico, impacto, perfuração e Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 2, for: 5, int: 1, pre: 1, vig: 4 },
    deslocamento: "12m | 8q",
    habilidades: [
      "SEDE DE SANGUE: Ataques causam +4d6 Sangue em personagens machucados ou sangrando.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA (C.C.) Teste 50+25 | Dano 4d12+10 perfuração.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS (C.C. x2) Teste 50+25 | Dano 4d8+10 corte.",
      },
      {
        nome: "ESTRAÇALHAR (Livre)",
        descricao: "Acerto Mordida: Dano 4d12+10 perfuração e Sangrando (Reflexos DT 30 reduz à metade e evita condição).",
      },
    ],
  },
  {
    id: "zumbi_de_sangue",
    nome: "Zumbi de Sangue",
    elemento: "Sangue",
    vd: 20,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 15 • 2d6 mental • NEX 25%+ é imune)",
    foto: "/assets/bestiario/Zumbi de sangue.webp",
    sentidos: "Percepção +10, Percepção às cegas",
    iniciativa: "20+5",
    defesa: 17,
    fortitude: "20+5",
    reflexos: "20+5",
    vontade: "1d20+5",
    pv_max: 45,
    pv_atual: 45,
    machucado: 22,
    resistencias: "Balístico, impacto e perfuração 5, Sangue 10",
    vulnerabilidades: "Morte",
    atributos: { agi: 2, for: 2, int: 0, pre: 1, vig: 2 },
    deslocamento: "9m | 6q",
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS (C.C. x2) Teste 2d20+5 | Dano 1d6+5 corte.",
      },
    ],
  },
  {
    id: "zumbi_de_sangue_bestial",
    nome: "Zumbi de Sangue Bestial",
    elemento: "Sangue",
    vd: 100,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 20 • 4d6 mental • NEX 45%+ é imune)",
    foto: "/assets/bestiario/zumbi_de_sangue_bestial.webp",
    sentidos: "Percepção 20+10, Percepção às cegas",
    iniciativa: "20+15",
    defesa: 23,
    fortitude: "30+10",
    reflexos: "20+5",
    vontade: "2d20+5",
    pv_max: 200,
    pv_atual: 200,
    machucado: 100,
    resistencias: "Balístico, impacto e perfuração 5, Sangue 10",
    vulnerabilidades: "Morte",
    atributos: { agi: 2, for: 3, int: 0, pre: 2, vig: 3 },
    deslocamento: "12m | 8q",
    habilidades: [
      "FURTIVO E LETAL: Ataque desprevenido: +O ataque, +2 dados de dano adicional do mesmo tipo.",
      "INSTINTO PREDATÓRIO: Deslocamento normal sem penalidade em Furtividade.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA DE SANGUE (C.C.) Teste 30+15 | Dano 2d10+5 perfuração.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS DE SANGUE (C.C. x2) Teste 30+15 | Dano 2d6+5 corte.",
      },
    ],
  },
  {
    id: "o_diabo",
    nome: "O Diabo",
    elemento: "Sangue",
    vd: 400,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 45 • 10d8 mental)",
    foto: "/assets/bestiario/o_diabo.webp",
    sentidos: "Percepção 60+25, Percepção às cegas",
    iniciativa: "60+35",
    defesa: 66,
    fortitude: "60+35",
    reflexos: "60+35",
    vontade: "60+35",
    pv_max: 1666,
    pv_atual: 1666,
    machucado: 833,
    imunidades: "Condições de atordoamento e paralisia, dano e efeitos de Sangue",
    resistencias: "Balístico, impacto e perfuração 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 6, for: 6, int: 6, pre: 6, vig: 6 },
    deslocamento: "18m | 12q",
    habilidades: [
      "ENIGMA DE MEDO: Desconhecido. Quando resolvido, perde Imunidade a Dano e bônus de testes de resistência reduzidos para +25.",
      "ARDILOSO: Pode escolher não ativar Presença Perturbadora.",
      "POTÊNCIA DE SANGUE: Recupera 50 PV/turno. Modificador +35 (FOR, VIG, PRE), +25 (AGI, INT).",
      "DECEPAR MÁSCARA: Resolve Enigma de Medo da Máscara do Desespero.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "ARMA SANGRENTA (C.C. x2, crítico x3) Teste 60+45 | Dano 2d10+50 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "CHIFRE DO DIABO (C.C., crítico x3) Teste 60+45 | Dano 2d8+50 Sangue.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "ARMA SANGRENTA (Distância x2 - Médio, crítico x3) Teste 60+45 | Dano 2d10+50 Sangue.",
      },
      {
        nome: "EXPLODIR EM SANGUE (Livre)",
        descricao: "Causa dano: Dano 10d6 Sangue. (2x/turno)",
      },
      {
        nome: "SANGRAR (Livre)",
        descricao: "Acerto Chifre: prende chifre, vulnerabilidade a Sangue. Ação padrão p/ remover (Dano 8d8 Sangue).",
      },
      {
        nome: "TRANSPORTAR PELO SANGUE (Movimento)",
        descricao: "Teletransporte para sangue exposto, ou adjacente a machucado/morrendo.",
      },
      {
        nome: "SENHOR DO SANGUE (Padrão)",
        descricao: "Invoca criaturas de Sangue VD 400 (uma vez por cena).",
      },
      {
        nome: "PACTO (Padrão)",
        descricao: "Oferece pacto: sofre 10d6 mental. Enlouquece: servo.",
      },
      {
        nome: "DESEJOS DE SANGUE (Completa)",
        descricao: "Alvos em alcance médio: atacam outro alvo adjacente (Vontade DT 45 evita).",
      },
    ],
  },
  {
    id: "mulher_afogada",
    nome: "Mulher Afogada",
    elemento: "Sangue",
    vd: 140,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 25 • 4d8 mental • NEX 50%+ é imune)",
    foto: "/assets/bestiario/Mulher Afogada.webp",
    sentidos: "Percepção 20+5, Percepção às cegas",
    iniciativa: "4d20+10",
    defesa: 28,
    fortitude: "30+10",
    reflexos: "40+10",
    vontade: "2d20+5",
    pv_max: 240,
    pv_atual: 240,
    machucado: 120,
    resistencias: "Balístico, Energia, impacto e perfuração 10, Sangue 20",
    vulnerabilidades: "Morte",
    atributos: { agi: 4, for: 3, int: 2, pre: 2, vig: 3 },
    deslocamento: "9m | 6q",
    habilidades: [
      "ENIGMA DE MEDO: Bloquear saídas de água/fechar registro/abrir torneiras. Consequência: perde Forma de Sangue.",
      "FORMA DE SANGUE: Padrão: Resistências 20 Balístico/Corte/Impacto/Perfuração/Sangue. Deslocamento 36m (24q), percorre canos. Ganha Ações: Afogar em Sangue, Arrancar Sangue, Invadir Órgãos.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão) - Forma Física",
        descricao: "MORDIDA (C.C.) Teste 30+15 | Dano 4d8+8 perfuração.",
      },
      {
        nome: "Agredir (Padrão) - Forma Física",
        descricao: "GARRAS (C.C. x2) Teste 40+15 | Dano 4d6+6 corte.",
      },
      {
        nome: "Agredir (Padrão) - Forma Física",
        descricao: "JATO DE SANGUE (Distância - Curto) Teste 40+10 | Dano 4d8+8 Sangue.",
      },
      {
        nome: "SUGAR SANGUE (Movimento) - Forma Física",
        descricao: "Devora corpo adjacente morto: recupera 40 PV.",
      },
      {
        nome: "AFOGAR EM SANGUE (Padrão) - Forma Líquida",
        descricao: "Asfixia alvo em alcance curto. Fort DT 24 para encerrar.",
      },
      {
        nome: "ARRANCAR SANGUE (Reação) - Forma Líquida",
        descricao: "Arrancada do corpo: Dano 6d6 Sangue e deixa fraca.",
      },
      {
        nome: "INVADIR ÓRGÃOS (Movimento) - Forma Líquida",
        descricao: "Asfixia: Dano 6d6 Sangue e enjoado.",
      },
    ],
  },
  // --- CRIATURAS DE MORTE ---
  {
    id: "aracnasita",
    nome: "Aracnasita",
    elemento: "Morte",
    vd: 80,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 20 • 4d6 mental • NEX 40%+ é imune)",
    foto: "/assets/bestiario/Aracnasita.webp",
    sentidos: "Percepção +10, Percepção às cegas",
    iniciativa: "30+10",
    defesa: 23,
    fortitude: "20+5",
    reflexos: "3d20+10",
    vontade: "1d20+5",
    pv_max: 140,
    pv_atual: 140,
    machucado: 70,
    imunidades: "Dano (removida se sofrer dano de fogo)",
    vulnerabilidades: "Energia",
    atributos: { agi: 3, for: 2, int: 1, pre: 1, vig: 2 },
    deslocamento: "12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Dano de Fogo remove imunidade até o próximo turno.",
      "PERCEPÇÃO TÁTIL: Percebe tudo em contato com a teia.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA (C.C.) Teste 30+15 | Dano 2d10+10 perfuração.",
      },
      {
        nome: "ESTACAR (Livre)",
        descricao: "Dano Mordida: +1d10 Morte, agarrado (Atletismo DT 20 solta).",
      },
      {
        nome: "DESOVAR ARANHAS (Reação)",
        descricao: "Fica machucada: 4 turnos de efeitos (Dano Mental/Morte, Aumento de Alcance, Cópia Aracnasita se alguém morrer).",
      },
      {
        nome: "DISPARAR TEIA (Movimento)",
        descricao: "Teia (3m quadrado): agarrado (Reflexos DT 20 evita). Sofre 2d8+10 Morte por turno.",
      },
    ],
  },
  {
    id: "carnical_preto_da_morte",
    nome: "Carniçal Preto da Morte",
    elemento: "Morte",
    vd: 200,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 30 • 6d6 mental • NEX 65%+ é imune)",
    foto: "/assets/bestiario/Carnical Preto Da Morte.webp",
    sentidos: "Percepção 30+15, Percepção às cegas",
    iniciativa: "40+15",
    defesa: 38,
    fortitude: "3d20+15",
    reflexos: "40+15",
    vontade: "30+15",
    pv_max: 400,
    pv_atual: 400,
    machucado: 200,
    imunidades: "Dano balístico",
    resistencias: "Corte, impacto e perfuração 10, Morte 20",
    vulnerabilidades: "Energia",
    atributos: { agi: 4, for: 4, int: 3, pre: 3, vig: 3 },
    deslocamento: "12m | 8q",
    habilidades: [
      "FÍSICO PARANORMAL: Pode saltar o dobro do deslocamento normal.",
      "INSTINTO MORTAL: Machucado: Hipnose (Livre) no início do turno, +1 ataque Garra da Morte.",
      "CORPO FECHADO: Mirar na cabeça ignora imunidade a balístico.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRA DA MORTE (C.C. x2) Teste 40+25 | Dano 4d10+20 Morte.",
      },
      {
        nome: "PANCADA PODEROSA (Reação)",
        descricao: "Acerto Crítico: empurra 6m. Dano 4d6 impacto se colidir.",
      },
      {
        nome: "COMANDO (Movimento)",
        descricao: "Comando (Perturbação, Vontade DT 29 evita).",
      },
      {
        nome: "HIPNOSE (Padrão)",
        descricao: "Controla mente (Vontade DT 29 evita). Máx 3 seres hipnotizados. Se alvo enlouquece, controle permanente.",
      },
      {
        nome: "REANIMAR CORPOS (Completa)",
        descricao: "Invoca 2d4+2 Esqueletos de Lodo (VD 20).",
      },
    ],
  },
  {
    id: "ceifador_espiral",
    nome: "Ceifador Espiral",
    elemento: "Morte",
    vd: 380,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 45 • 9d8 mental)",
    foto: "/assets/bestiario/Ceifador Espiral.webp",
    sentidos: "Percepção 50+20, Percepção às cegas",
    iniciativa: "50+20",
    defesa: 58,
    fortitude: "50+25",
    reflexos: "5d20+25",
    vontade: "50+25",
    pv_max: 999,
    pv_atual: 999,
    machucado: 499,
    imunidades: "Condições de paralisia e lento, efeitos e dano de Morte",
    resistencias: "Dano 50",
    vulnerabilidades: "Energia",
    atributos: { agi: 5, for: 5, int: 5, pre: 5, vig: 5 },
    deslocamento: "15m | 10q",
    habilidades: [
      "ENIGMA DE MEDO: Transforma espiral em linha. Consequência: Perde RD e Cinzas das Terras Desoladas.",
      "DECEPAR: Acerto Crítico: PV reduzido a 25, -1 atributo permanente. Se PV <= 25, morte instantânea. Recupera 50 PV temp +1d10 dano por morte.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "FOICE DA MORTE (C.C. x2) Teste 50+40 | Dano 5d10+20 Morte.",
      },
      {
        nome: "TRANSPORTE PELO PÓ (Movimento)",
        descricao: "Teletransporte na área Cinzas das Terras Desoladas. Seguido de ataque Foice da Morte (Livre).",
      },
      {
        nome: "CONTEMPLAR A ESPIRAL (Completa)",
        descricao: "Dano 10d10+30 mental (Vontade DT 43 reduz à metade).",
      },
      {
        nome: "CINZAS DAS TERRAS DESOLADAS (Completa)",
        descricao: "Dano 10d10+20 Morte. Enjoado (Fort DT 43 reduz à metade). Dano 20 Morte/turno na área (Alcance Longo).",
      },
    ],
  },
  {
    id: "enraizado",
    nome: "Enraizado",
    elemento: "Morte",
    vd: 120,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 20 • 4d6 mental • NEX 50%+ é imune)",
    foto: "/assets/bestiario/Enraizado.webp",
    sentidos: "Percepção +10, Percepção às cegas",
    iniciativa: "30+10",
    defesa: 28,
    fortitude: "30+10",
    reflexos: "30+10",
    vontade: "1d20+5",
    pv_max: 140,
    pv_atual: 140,
    machucado: 70,
    resistencias: "Corte, impacto e perfuração 10, Morte 20",
    vulnerabilidades: "Energia",
    atributos: { agi: 3, for: 3, int: 1, pre: 1, vig: 3 },
    deslocamento: "9m | 6q",
    habilidades: [
      "IMORTALIDADE: Morte: Poça. Retorna 1d2 rodadas com 70 PV. Destruído se sofrer 20 dano Fogo/Energia.",
      "VENENO PÚTRIDO: Primeiro dano Punho Espinhento: envenenado. Fort DT 23 falha: 4d12 Morte/turno. Passa: cura.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PUNHO ESPINHENTO (C.C. x2) Teste 30+15 | Dano 2d8+8 impacto mais 2d12 Morte.",
      },
    ],
  },
  {
    id: "escutado",
    nome: "Escutado",
    elemento: "Morte",
    vd: 160,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 25 • 4d8 mental • NEX 55%+ é imune)",
    foto: "/assets/bestiario/Escutado.webp",
    sentidos: "Percepção 20+10, Percepção às cegas",
    iniciativa: "40+10",
    defesa: 29,
    fortitude: "30+10",
    reflexos: "40+10",
    vontade: "2d20+5",
    pv_max: 290,
    pv_atual: 290,
    machucado: 145,
    imunidades: "Dano (removida se Enigma resolvido)",
    resistencias: "Morte 10, Energia 10",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 4, for: 3, int: 1, pre: 2, vig: 3 },
    deslocamento: "12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Tocar melodia 4 rodadas ininterruptas. Consequência: Perde Imunidade a Dano.",
      "MULTIPLICAÇÃO MELÓDICA: Ouvindo melodia, manifesta cópia (145 PV) que multiplica no próximo turno.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA (C.C. x2) Teste 30+20 | Dano 3d6+10 perfuração.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "CABEÇA ARREMESSADA (Distância x2 - Curto) Teste 40+15 | Dano 1d10+10 impacto.",
      },
      {
        nome: "VOMITAR LODO (Movimento)",
        descricao: "Cópia despeja jorro de Lodo: Dano 4d10+10 Morte, lento (Reflexos DT 25 reduz à metade e evita condição).",
      },
    ],
  },
  {
    id: "esqueleto_de_lodo",
    nome: "Esqueleto de Lodo",
    elemento: "Morte",
    vd: 20,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 14 • 2d4 mental • NEX 25%+ é imune)",
    foto: "/assets/bestiario/esqueleto_lodo.webp",
    sentidos: "Percepção 1d20, Percepção às cegas",
    iniciativa: "2d20",
    defesa: 14,
    fortitude: "2d20",
    reflexos: "2d20+5",
    vontade: "2d20",
    pv_max: 40,
    pv_atual: 40,
    machucado: 20,
    resistencias: "Corte, impacto e perfuração 5, Morte 10",
    vulnerabilidades: "Energia",
    atributos: { agi: 2, for: 2, int: 0, pre: 1, vig: 1 },
    deslocamento: "6m | 4q",
    habilidades: [
      "IMORTALIDADE: Morte: Poça. Retorna 1d3 rodadas com 20 PV. Destruído se sofrer dano Fogo/Energia.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS (Corpo a corpo x2) Teste 2d20+5 | Dano 2d6+2 corte.",
      },
      {
        nome: "ESPIRAL DE LODO (Completa)",
        descricao: "Linha reta 9m. Dano 2d10 Morte (Reflexos DT 14 reduz à metade).",
      },
    ],
  },
  {
    id: "marionete",
    nome: "Marionete",
    elemento: "Morte",
    vd: 280,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 35 • 8d6 mental • NEX 85%+ é imune)",
    foto: "/assets/bestiario/Marionete.webp",
    sentidos: "Percepção 50+15, Percepção às cegas",
    iniciativa: "30+15",
    defesa: 40,
    fortitude: "20+10",
    reflexos: "30+15",
    vontade: "5d20+20",
    pv_max: 700,
    pv_atual: 700,
    machucado: 350,
    resistencias: "Corte, impacto, perfuração e Morte 20",
    vulnerabilidades: "Energia",
    atributos: { agi: 3, for: 5, int: 1, pre: 5, vig: 2 },
    deslocamento: "6m | 4q",
    habilidades: [
      "MOMENTO PASSIVO: Ignora redução de deslocamento e terreno difícil. Ignora dano/efeitos que dependem de toque no chão.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "FOICE DA MORTE (C.C. x2) Teste 50+30 | Dano 10d8+10 Morte.",
      },
      {
        nome: "REFLEXOS GUIADOS POR CORDA (Reação)",
        descricao: "Alvo adjacente: 1 ataque Foice da Morte.",
      },
      {
        nome: "IRONIA DO DESTINO (Completa)",
        descricao: "2x Foice da Morte. Acerto 2º ataque: agarra alvo, desloca 6m. Dano da Marionete é dividido entre ela e o alvo.",
      },
    ],
  },
  {
    id: "mumia_xipofaga",
    nome: "Múmia Xipófaga",
    elemento: "Morte",
    vd: 240,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 30 • 6d8 mental • NEX 75%+ é imune)",
    foto: "/assets/bestiario/mumia_xipofaga.webp",
    sentidos: "Percepção 30+10, Percepção às cegas",
    iniciativa: "5d20+15",
    defesa: 35,
    fortitude: "40+15",
    reflexos: "50+15",
    vontade: "30+10",
    pv_max: 400,
    pv_atual: 400,
    machucado: 200,
    resistencias: "Corte, impacto e perfuração 10, Morte 20",
    vulnerabilidades: "Energia, fogo",
    atributos: { agi: 5, for: 4, int: 2, pre: 3, vig: 4 },
    deslocamento: "9m | 6q",
    habilidades: [
      "FAIXAS DA PERMANÊNCIA: 0 PV: pode agir até o fim do próximo turno.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRA ENFAIXADA (C.C. x2) Teste 40+30 | Dano 4d8+30 corte.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "VOMITAR LODO (Distância x2 - Curto) Teste 50+25 | Dano 3d6+30 Morte mais 3d8 mental.",
      },
      {
        nome: "AGARRADA MUMIFICADORA (Livre)",
        descricao: "Acerto Garra: agarra alvo (teste 40+30). Sofre 4d8+30 Morte/turno. Múmia recupera PV. 0 PV: vira Esqueleto de Lodo.",
      },
      {
        nome: "AMALGAMAR (Padrão)",
        descricao: "0 PV: amalgama ser morto/criatura Morte. Recupera 200 PV, 3x Garra, +5 Dano. 2ª vez: +200 PV, 4x Garra, +10 Dano.",
      },
    ],
  },
  {
    id: "nidere",
    nome: "Nidere",
    elemento: "Morte",
    vd: 320,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 35 • 8d6 mental • NEX 95%+ é imune)",
    foto: "/assets/bestiario/Nidere.webp",
    sentidos: "Percepção 40+25, Faro",
    iniciativa: "50+25",
    defesa: 50,
    fortitude: "50+25",
    reflexos: "50+25",
    vontade: "40+15",
    pv_max: 800,
    pv_atual: 800,
    machucado: 400,
    resistencias: "Corte, impacto, perfuração e Morte 20",
    vulnerabilidades: "Energia",
    atributos: { agi: 5, for: 5, int: 3, pre: 4, vig: 5 },
    deslocamento: "24m | 18q",
    habilidades: [
      "ENIGMA DE MEDO: Destruir a origem no covil. Consequência: Perde Regeneração Acelerada e Senso de Direção Perfeito.",
      "CAÇADOR VELOZ: Deslocamento normal sem penalidade em Furtividade.",
      "REGENERAÇÃO ACELERADA: Cura Acelerada 50 (Perde se Enigma resolvido).",
      "SENSO DE DIREÇÃO PERFEITO: +2O em Percepção e Sobrevivência (Perde se Enigma resolvido).",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRA INVERTIDA (C.C. x2) Teste 50+35 | Dano 4d10+40 Morte.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA INVERTIDA (C.C.) Teste 50+35 | Dano 4d12+40 Morte.",
      },
      {
        nome: "REVERTER (Livre)",
        descricao: "Dano Garras: alvo enjoado.",
      },
      {
        nome: "RASTREAR E ABATER (Livre)",
        descricao: "Dano +6d6 contra seres desprevenidos.",
      },
    ],
  },
  {
    id: "sempiternal",
    nome: "Sempiternal",
    elemento: "Morte",
    vd: 360,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 40 • 8d8 mental)",
    foto: "/assets/bestiario/Sempiternal.webp",
    sentidos: "Percepção 50+20",
    iniciativa: "50+25",
    defesa: 53,
    fortitude: "40+20",
    reflexos: "5d20+30",
    vontade: "50+25",
    pv_max: 990,
    pv_atual: 990,
    machucado: 445,
    imunidades: "Condições lento e de paralisia, e dano e efeitos de Morte",
    resistencias: "Corte, impacto e perfuração 20",
    vulnerabilidades: "Energia",
    atributos: { agi: 5, for: 5, int: 4, pre: 5, vig: 4 },
    deslocamento: "12m | 8q",
    habilidades: [
      "TOQUE ACELERADOR: Dano: envelhece 1d10 anos. 20+ anos: fraco, 40+ anos: debilitado, 60+ anos: morre.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "DEDOS ALONGADOS (C.C. x4) Teste 50+40 | Dano 4d10 Morte mais envelhecimento.",
      },
      {
        nome: "CORRENTES DE LODO (Movimento)",
        descricao: "Dano 20d6 Morte (Fort DT 40 reduz à metade). Machucado: vulnerabilidade Morte. 0 PV: vira Enraizado.",
      },
    ],
  },
  {
    id: "succ",
    nome: "Succ",
    elemento: "Morte",
    vd: 40,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 15 • 3d6 mental • NEX 30%+ é imune)",
    foto: "/assets/bestiario/Succ.webp",
    sentidos: "Percepção +5, Percepção às cegas",
    iniciativa: "40+5",
    defesa: 20,
    fortitude: "1d20+5",
    reflexos: "40+10",
    vontade: "1d20+5",
    pv_max: 65,
    pv_atual: 65,
    machucado: 32,
    resistencias: "Corte, impacto e perfuração 5, Morte 10",
    vulnerabilidades: "Energia",
    atributos: { agi: 4, for: 2, int: 0, pre: 1, vig: 1 },
    deslocamento: "12m | 8q",
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA (C.C.) Teste 40+10 | Dano 2d8+2 perfuração.",
      },
      {
        nome: "SUCÇÃO (Livre)",
        descricao: "Acerto Mordida: prende dentes (Fort DT 17 evita). Falha: inconsciente, 0 PV no próximo turno. Succ sofre 10+ dano, solta alvo.",
      },
    ],
  },
  {
    id: "o_deus_da_morte",
    nome: "O Deus da Morte",
    elemento: "Morte",
    vd: 400,
    tipo: "Relíquia Grande",
    presenca: "Perturbadora (DT 45 • 10d8 mental)",
    foto: "/assets/bestiario/o_deus_da_morte.webp",
    sentidos: "Percepção 50+30, Percepção às cegas",
    iniciativa: "60+30",
    defesa: 60,
    fortitude: "70+35",
    reflexos: "6d20+35",
    vontade: "50+35",
    pv_max: 2000,
    pv_atual: 2000,
    machucado: 1000,
    imunidades: "Condições de atordoamento e paralisia, dano e efeitos de Morte",
    resistencias: "Corte, impacto e perfuração 20",
    vulnerabilidades: "Energia",
    atributos: { agi: 6, for: 6, int: 5, pre: 5, vig: 7 },
    deslocamento: "15m | 10q",
    habilidades: [
      "ENIGMA DE MEDO: Desconhecido. Quando resolvido, perde Ciclo Infinito e Senhor do Tempo.",
      "CICLO INFINITO: Recupera 50 PV/turno. 0 PV: vira poça, manifesta-se em cadáver/alvo de maior NEX.",
      "POTÊNCIA DE MORTE: Modificador +35 (FOR, VIG, PRE), +25 (AGI, INT).",
      "SENHOR DO TEMPO: Rola 1d20/rodada para turno adicional.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "SOCO ESPIRAL (C.C. x2) Teste 60+45 | Dano 5d10+50 Morte.",
      },
      {
        nome: "AGARRÃO (Livre)",
        descricao: "Acerto Soco Espiral: agarra alvo (teste 60+47).",
      },
      {
        nome: "CONTROLAR RELÓGIO INTERNO (Livre)",
        descricao: "Encerra 2 condições que o afetem.",
      },
      {
        nome: "CONTROLAR MORTOS (Movimento)",
        descricao: "Controla criatura Morte em alcance longo para atacar.",
      },
      {
        nome: "ESPIRAL DESCENDENTE (Movimento)",
        descricao: "Alvo agarrado: envelhece 3d20 anos. Dano mental = anos envelhecidos.",
      },
      {
        nome: "ESPIRAL DESTRUTIVA (Padrão)",
        descricao: "Dano 10d10+50 Morte (Fort DT 45 reduz à metade).",
      },
    ],
  },
  // --- CRIATURAS DE CONHECIMENTO ---
  {
    id: "anjo",
    nome: "Anjo",
    elemento: "Conhecimento",
    vd: 380,
    tipo: "Criatura Enorme",
    presenca: "Perturbadora (DT 40 • 10d6 mental)",
    foto: "/assets/bestiario/Anjo.webp",
    sentidos: "Percepção 50+25, Percepção às cegas",
    iniciativa: "40+25",
    defesa: 57,
    fortitude: "50+25",
    reflexos: "4d20+25",
    vontade: "50+30",
    pv_max: 1111,
    pv_atual: 1111,
    machucado: 555,
    imunidades: "Condições de paralisia, dano e efeitos de Conhecimento",
    resistencias: "Dano 50",
    vulnerabilidades: "Sangue",
    atributos: { agi: 4, for: 5, int: 5, pre: 5, vig: 5 },
    deslocamento: "Voo 24m | 16q",
    habilidades: [
      "ENIGMA DE MEDO: Falha em julgar corretamente. Consequência: Perde RD, Voo, Julgamento.",
      "JULGAMENTO: Dano Conhecimento: sofre metade em Dano Mental. Sanidade 0: morre instantaneamente.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "ASAS DO CONHECIMENTO (C.C. x2) Teste 50+40 | Dano 4d10+40 Conhecimento.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "OLHARES DO SABER (Distância x2 - Longo) Teste 40+40 | Dano 6d8+20 Conhecimento.",
      },
      {
        nome: "FAIXAS DETENTORAS (Livre)",
        descricao: "Acerto Asas: agarra (teste 50+45), fascinado.",
      },
      {
        nome: "CHAMAS REVELADORAS (Padrão)",
        descricao: "Dano 10d8 Conhecimento (Vontade DT 43 reduz à metade). Auréola: ignora Furtividade/Invisibilidade.",
      },
      {
        nome: "RAIO DOURADO (Completa)",
        descricao: "Dano 15d8+50 Conhecimento (Reflexos DT 43 reduz à metade).",
      },
    ],
  },
  {
    id: "bicho_papao",
    nome: "Bicho-Papão",
    elemento: "Conhecimento",
    vd: 300,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 35 • 7d8 mental • NEX 90%+ é imune)",
    foto: "/assets/bestiario/Bicho papao.webp",
    sentidos: "Percepção 50+20, Percepção às cegas",
    iniciativa: "50+20",
    defesa: 41,
    fortitude: "40+15",
    reflexos: "50+25",
    vontade: "50+20",
    pv_max: 750,
    pv_atual: 750,
    machucado: 375,
    resistencias: "Balístico, corte, impacto e Conhecimento 20",
    vulnerabilidades: "Sangue",
    atributos: { agi: 5, for: 4, int: 3, pre: 5, vig: 4 },
    deslocamento: "15m | 10q",
    habilidades: [
      "TAMANHO ADAPTÁVEL: Reduz corpo p/ esconderijo. Deslocamento normal em Furtividade/Escalada.",
      "TORMENTO INFANTIL: Desprevenido se ouvir cantiga. Choro: usa ações p/ silenciar.",
      "DESTRUIR MENTE: Dano Garras: +1d8 mental.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS ATORMENTADORAS (C.C. x3) Teste 50+35 | Dano 4d10+10 Conhecimento.",
      },
      {
        nome: "ATORMENTAR (Movimento)",
        descricao: "Dano 3d8 mental (Vontade DT 30 reduz à metade). Escondido: +3d8 dano.",
      },
      {
        nome: "SALTAR E ASSUSTAR (Completa)",
        descricao: "Escondido: Alvo sofre 10d8 mental (Vontade DT 35 reduz à metade).",
      },
    ],
  },
  {
    id: "espreitador",
    nome: "Espreitador",
    elemento: "Conhecimento",
    vd: 220,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 30 • 7d6 mental • NEX 70%+ é imune)",
    foto: "/assets/bestiario/Espreitador.webp",
    sentidos: "Percepção 30+15, Percepção às cegas",
    iniciativa: "40+15",
    defesa: 34,
    fortitude: "2d20+10",
    reflexos: "4d20+15",
    vontade: "30+15",
    pv_max: 500,
    pv_atual: 500,
    machucado: 250,
    imunidades: "Dano (removida se Enigma resolvido)",
    vulnerabilidades: "Sangue",
    atributos: { agi: 4, for: 2, int: 3, pre: 3, vig: 2 },
    deslocamento: "12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Alvo dormindo no escuro o atrai para fora. Consequência: Perde Imunidade a Dano.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (C.C. x2) Teste 2d20+10 | Dano 1d6+2 impacto.",
      },
      {
        nome: "CORRER PELAS FRESTAS (Movimento)",
        descricao: "Teletransporte alcance longo: fresta pequena.",
      },
      {
        nome: "ESPREITAR (Completa)",
        descricao: "Alvo dormindo: Dano 10d6 mental (Vontade DT 30 reduz à metade). Enlouquece: cria Cópia Observada.",
      },
      {
        nome: "CÓPIA OBSERVADA (Padrão)",
        descricao: "Cria cópia com ficha do alvo, 20 PV, dano Conhecimento.",
      },
    ],
  },
  {
    id: "existido",
    nome: "Existido",
    elemento: "Conhecimento",
    vd: 20,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 14 • 1d6 mental • NEX 25%+ é imune)",
    foto: "/assets/bestiario/existido.webp",
    sentidos: "Percepção 20+5, Percepção às cegas",
    iniciativa: "1d20+5",
    defesa: 13,
    fortitude: "2d20",
    reflexos: "1d20",
    vontade: "2d20+10",
    pv_max: 36,
    pv_atual: 36,
    machucado: 18,
    resistencias: "Balístico, corte e impacto 5, Conhecimento 10",
    vulnerabilidades: "Sangue",
    atributos: { agi: 1, for: 1, int: 4, pre: 2, vig: 2 },
    deslocamento: "9m | 6q",
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (C.C.) Teste 1d20+5 | Dano 1d4+1 impacto.",
      },
      {
        nome: "BRILHO ENLOUQUECEDOR (Livre)",
        descricao: "1/rodada. Todos em alcance médio sofrem 1d6 mental (Vontade DT 14 reduz à metade).",
      },
      {
        nome: "FORTALECIMENTO PARANORMAL (Movimento)",
        descricao: "Causa dano mental: +O em testes AGI, FOR, VIG. Pancadas causam +2d4 Conhecimento.",
      },
    ],
  },
  {
    id: "lembrado",
    nome: "Lembrado",
    elemento: "Conhecimento",
    vd: 100,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 20 • 4d6 mental • NEX 45%+ é imune)",
    foto: "/assets/bestiario/Lembrado.webp",
    sentidos: "Percepção 20+10, Percepção às cegas",
    iniciativa: "2d20+10",
    defesa: 22,
    fortitude: "20+5",
    reflexos: "2d20",
    vontade: "2d20+10",
    pv_max: 180,
    pv_atual: 180,
    machucado: 90,
    resistencias: "Balístico, corte e impacto 10, Conhecimento 20",
    vulnerabilidades: "Sangue",
    atributos: { agi: 2, for: 2, int: 4, pre: 2, vig: 2 },
    deslocamento: "9m | 6q",
    habilidades: [
      "AURA MANIFESTADA: Personagens em alcance curto sofrem -2O em todos os testes.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (C.C. x2) Teste 2d20+5 | Dano 2d4+7 impacto.",
      },
      {
        nome: "EXPANDIR AURA (Padrão)",
        descricao: "Todos em alcance curto sofrem 6d6 mental (Vontade DT 20 reduz à metade).",
      },
    ],
  },
  {
    id: "ocioso",
    nome: "Ocioso",
    elemento: "Conhecimento",
    vd: 260,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 35 • 8d6 mental • NEX 80%+ é imune)",
    foto: "/assets/bestiario/ocioso.webp",
    sentidos: "Percepção 50+15, Percepção às cegas",
    iniciativa: "2d20",
    defesa: 37,
    fortitude: "30+15",
    reflexos: "2d20",
    vontade: "50+20",
    pv_max: 390,
    pv_atual: 390,
    machucado: 195,
    resistencias: "Balístico, corte, impacto e Conhecimento 20",
    vulnerabilidades: "Sangue",
    atributos: { agi: 1, for: 5, int: 1, pre: 5, vig: 3 },
    deslocamento: "Voo 0m | 0q",
    habilidades: [
      "SEMPRE PRESENTE: Visível apenas para o alvo escolhido. Invisível para todos os outros.",
    ],
    acoes: [
      {
        nome: "RETALIAÇÃO (Reação)",
        descricao: "Atacado: teletransporte adjacente, ataque C.C. (Teste 50+30 | Dano 4d10+20 impacto não letal).",
      },
      {
        nome: "PERMANECER PRÓXIMO (Livre)",
        descricao: "Teletransporte no campo de visão do alvo.",
      },
      {
        nome: "ATERRORIZAR (Completa)",
        descricao: "Alvo adjacente: Dano 4d10+10 mental.",
      },
    ],
  },
  {
    id: "parasita_de_culpa",
    nome: "Parasita de Culpa",
    elemento: "Conhecimento",
    vd: 60,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 20 • 2d6 mental • NEX 35%+ é imune)",
    foto: "/assets/bestiario/Parasita de Culpa.webp",
    sentidos: "Percepção +4, Percepção às cegas",
    iniciativa: "1d20+10",
    defesa: 15,
    fortitude: "1d20",
    reflexos: "2d20+10",
    vontade: "40+10",
    pv_max: 90,
    pv_atual: 90,
    machucado: 45,
    imunidades: "Dano (exceto hospedeiro)",
    vulnerabilidades: "Sangue",
    atributos: { agi: 2, for: 1, int: 4, pre: 4, vig: 1 },
    deslocamento: "6m | 4q",
    habilidades: [
      "ENIGMA DE MEDO: Derrotar manifestações dentro do sonho compartilhado. Consequência: Perde Imunidade a Dano.",
      "DEVORAR CULPA: Fixa em alvo dormindo: expande influência, cria sonho compartilhado.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (C.C.) Teste 1d20+4 | Dano 1d4 impacto.",
      },
      {
        nome: "FIXAR (Completa)",
        descricao: "Tenta fixar-se em alvo dormindo (Furtividade 20+15 vs Percepção com penalidade).",
      },
      {
        nome: "ATORMENTAR (Completa)",
        descricao: "Fixado: Dano 2d6 mental por cena (Vontade DT 20 reduz à metade).",
      },
      {
        nome: "CÓPIAS DO HOSPEDEIRO (Completa)",
        descricao: "Cria cópia Conhecimento (20 PV) com estatísticas do hospedeiro. Máx 4 cópias.",
      },
    ],
  },
  {
    id: "rastejador_sombrio",
    nome: "Rastejador Sombrio",
    elemento: "Conhecimento",
    vd: 180,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 25 • 6d6 mental • NEX 60%+ é imune)",
    foto: "/assets/bestiario/rastejador_sombrio.webp",
    sentidos: "Percepção 30+15, Percepção às cegas",
    iniciativa: "40+15",
    defesa: 41,
    fortitude: "30+15",
    reflexos: "40+15",
    vontade: "30+10",
    pv_max: 330,
    pv_atual: 330,
    machucado: 165,
    resistencias: "Balístico, corte e impacto 10, Conhecimento 20",
    vulnerabilidades: "Sangue",
    atributos: { agi: 4, for: 3, int: 3, pre: 3, vig: 3 },
    deslocamento: "12m | 8q",
    habilidades: [
      "VULNERABILIDADE A LUZ: Luz forte: -10 Defesa, perde Desespero, Rastejar e Tentáculos.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "TOQUE DA DOR (C.C. x3) Teste 40+20 | Dano 4d8+5 Conhecimento.",
      },
      {
        nome: "RASTEJAR (Livre)",
        descricao: "Cobertura/Camuflagem parcial: +10 Furtividade, deslocamento normal.",
      },
      {
        nome: "TENTÁCULOS DAS SOMBRAS (Movimento)",
        descricao: "Agarra 3 alvos em alcance médio (Reflexos DT 28 evita). Dano 4d6 mental por turno (agarrado).",
      },
      {
        nome: "DESESPERO (Livre)",
        descricao: "Dano Toque: Sofre mesma quantidade de Dano Mental (Vontade DT 25 reduz à metade).",
      },
    ],
  },
  {
    id: "silhueta",
    nome: "Silhueta",
    elemento: "Conhecimento",
    vd: 360,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 40 • 8d8 mental)",
    foto: "/assets/bestiario/silhueta.webp",
    sentidos: "Percepção 50+25, Percepção às cegas",
    iniciativa: "40+20",
    defesa: 55,
    fortitude: "40+20",
    reflexos: "4d20+20",
    vontade: "5d20+25",
    pv_max: 500,
    pv_atual: 500,
    machucado: 250,
    imunidades: "Condições de paralisia, efeitos e dano de Conhecimento, manobras de combate",
    resistencias: "Dano 30",
    vulnerabilidades: "Sangue",
    atributos: { agi: 4, for: 4, int: 5, pre: 5, vig: 4 },
    deslocamento: "12m | 8q",
    habilidades: [
      "AURA TANGÍVEL: Toca: Dano 20d12 Conhecimento (Fort DT 42 reduz à metade). 0 PV: desintegrado.",
      "CONHECIMENTO VERDADEIRO: Testes INT/PRE: +25, AGI/FOR/VIG: +20.",
    ],
    acoes: [
      {
        nome: "REESCREVER A REALIDADE (Livre)",
        descricao: "Deslocamento: transforma objetos em alcance curto.",
      },
      {
        nome: "TOQUE DEVASTADOR (Padrão)",
        descricao: "Toca 2 alvos: Dano Aura Tangível.",
      },
    ],
  },
  {
    id: "vulto",
    nome: "Vulto",
    elemento: "Conhecimento",
    vd: 40,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 15 • 3d6 mental • NEX 30%+ é imune)",
    foto: "/assets/bestiario/vulto.webp",
    sentidos: "Percepção 20+5, Percepção às cegas",
    iniciativa: "40+5",
    defesa: 19,
    fortitude: "1d20",
    reflexos: "40+5",
    vontade: "2d20+5",
    pv_max: 60,
    pv_atual: 60,
    machucado: 30,
    resistencias: "Balístico, corte e perfuração 5, Conhecimento 10",
    vulnerabilidades: "Sangue",
    atributos: { agi: 4, for: 2, int: 2, pre: 2, vig: 1 },
    deslocamento: "12m | 8q",
    habilidades: [
      "AURA TANGÍVEL: Ataques contra alvo sob condição de medo causam +2d6 Conhecimento.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "TOQUE MACABRO (C.C. x2) Teste 40+10 | Dano 2d6 Conhecimento.",
      },
      {
        nome: "PLANTAR PARANOIA (Completa)",
        descricao: "Alvos em alcance médio: abalado (Vontade DT 15 evita). Abalado vira Apavorado. Escondido: -O no teste.",
      },
    ],
  },
  {
    id: "Estrangeiro",
    nome: "Estrangeiro",
    elemento: "Conhecimento",
    vd: 340,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 40 • 10d6 mental • NEX 99%+ é imune)",
    foto: "/assets/bestiario/Estrangeiro.webp",
    sentidos: "Percepção 50+25, Percepção às cegas",
    iniciativa: "30+20",
    defesa: 50,
    fortitude: "30+15",
    reflexos: "3d20+20",
    vontade: "50+25",
    pv_max: 750,
    pv_atual: 750,
    machucado: 375,
    imunidades: "Dano",
    vulnerabilidades: "Sangue",
    atributos: { agi: 3, for: 5, int: 5, pre: 5, vig: 3 },
    deslocamento: "Voo 15m | 10q",
    habilidades: [
      "ENIGMA DE MEDO: Decifrar intenções/linguagem. Consequência: Perde Imunidade a Dano, não pode usar Incubar.",
      "POTÊNCIA DE ENERGIA: Modificador +35 (AGI, INT), +25 (FOR, PRE, VIG).",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "TOQUE SUTIL (C.C. x3) Teste 50d20+35 | Dano 4d8+10 Conhecimento.",
      },
      {
        nome: "Agredir (Padrão)",
        descricao: "RAJADA PSÍQUICA (Distância x2 - Extremo) Teste 50d20+35 | Dano 4d10+20 Conhecimento.",
      },
      {
        nome: "COMANDAR (Livre)",
        descricao: "Dano Rajada: domina mente (Vontade DT 35). Ordens: Atacar/Render-se/Fugir.",
      },
      {
        nome: "APAGAR MEMÓRIA (Livre)",
        descricao: "Insano: controle mental ou apaga memória (1d4 Sanidade).",
      },
      {
        nome: "OBLIVIO (Livre)",
        descricao: "Dano Toque: alvo esquece Anfitrião (Vontade DT 30 evita).",
      },
      {
        nome: "INCUBAR (Completa)",
        descricao: "Toca alvo alheio: insere larva. Sofre 1d6 mental/cena. Sanidade 0: novo Anfitrião.",
      },
    ],
  },
  {
    id: "mascara_do_desespero",
    nome: "Máscara do Desespero",
    elemento: "Conhecimento",
    vd: 400,
    tipo: "Relíquia Minúsculo",
    presenca: "Perturbadora (DT 45 • 10d8 mental)",
    foto: "/assets/bestiario/mascara_do_desespero.webp",
    sentidos: "Percepção 60+35, Percepção às cegas",
    iniciativa: "40+25",
    defesa: 55,
    fortitude: "50+35",
    reflexos: "40+25",
    vontade: "6d20+35",
    pv_max: 1200,
    pv_atual: 1200,
    machucado: 600,
    imunidades: "Condições, dano (removida se Enigma resolvido)",
    vulnerabilidades: "Sangue",
    atributos: { agi: 4, for: 4, int: 6, pre: 6, vig: 5 },
    deslocamento: "Voo 12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Quebrar o Equilíbrio ou confrontar com o Diabo. Consequência: Perde Imunidade a Dano, perde Onipresença.",
      "POTÊNCIA DO CONHECIMENTO: Modificador +35 (INT, PRE, VIG), +25 (AGI, FOR).",
      "DESTRONAR O ANFITRIÃO: Resolve Enigma de Medo do Anfitrião.",
    ],
    acoes: [
      {
        nome: "CONJURAÇÃO VERDADEIRA (Livre)",
        descricao: "Conjura ritual Conhecimento (qualquer círculo, PE max 20, DT 45). (1x/turno).",
      },
      {
        nome: "ONIPRESENÇA (Movimento)",
        descricao: "Teletransporte para qualquer sombra. Sabe tudo, ignora Furtividade/Invisibilidade.",
      },
      {
        nome: "REESCREVER REALIDADE (Padrão)",
        descricao: "Altera objetos (Reflexos DT 45 evita). Seres: 10d6 Conhecimento, 10d6 mental, 1 condição (Vontade DT 45 reduz à metade/evita).",
      },
    ],
  },
  // --- CRIATURAS DE ENERGIA ---
  {
    id: "anarquico_descontrolado",
    nome: "Anárquico Descontrolado",
    elemento: "Energia",
    vd: 120,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 21 • 4d6 mental • NEX 50%+ é imune)",
    foto: "/assets/bestiario/anarquico.webp",
    sentidos: "Percepção 20+5, Visão no escuro",
    iniciativa: "40+10",
    defesa: 28,
    fortitude: "30+10",
    reflexos: "4d20+10",
    vontade: "2d20+5",
    pv_max: 120,
    pv_atual: 120,
    machucado: 60,
    resistencias: "Balístico, corte e perfuração 10, Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 4, for: 3, int: 2, pre: 2, vig: 3 },
    deslocamento: "12m | 8q",
    habilidades: [
      "COMPORTAMENTO ERRÁTICO: 3x 1d6 - Ações aleatórias (Salto/Ataque, Teletransporte, Explosão, Risada, Toque). Perde Resistência/Dano se falhar nas ações.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA ENERGÉTICA (C.C. x2) Teste 40+15 | Dano 4d12 impacto.",
      },
      {
        nome: "ACELERAÇÃO (Livre)",
        descricao: "Dano Pancada: alvo sofre 4d12 Energia se realizar 2 ações no próximo turno.",
      },
      {
        nome: "AUTODESTRUIÇÃO (Movimento)",
        descricao: "Dano 8d12 Energia em alcance curto (Reflexos DT 25 reduz à metade). Morre.",
      },
    ],
  },
  {
    id: "anomalia",
    nome: "Anomalia",
    elemento: "Energia",
    vd: 380,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 45 • 9d8 mental)",
    foto: "/assets/bestiario/Anomalia.webp",
    sentidos: "Percepção 5d20, Visão no escuro",
    iniciativa: "5d20",
    defesa: 50,
    fortitude: "50+15",
    reflexos: "50+15",
    vontade: "50+15",
    pv_max: 1000,
    pv_atual: 1000,
    machucado: 500,
    imunidades: "Dano e todas as condições (removida se Enigma resolvido)",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 5, for: 5, int: 5, pre: 5, vig: 5 },
    deslocamento: "0m | 0q",
    habilidades: [
      "ENIGMA DE MEDO: Mergulhar na anomalia. Consequência: Transforma-se em ser/objeto aleatório por 2d4 rodadas, perde Imunidade a Dano/Condições.",
      "IMATERIAL: Imune a Dano/Condições.",
      "EXISTÊNCIA IMPOSSÍVEL: Existe apenas em objeto com porta aberta. Surge ao abrir porta.",
    ],
    acoes: [
      {
        nome: "ROMPER CONSCIÊNCIA (Livre)",
        descricao: "Alvo aleatório: Dano 10d6 mental (Vontade DT 41 reduz à metade). Insano: absorvida.",
      },
      {
        nome: "MANIPULAR ONDAS DA EXISTÊNCIA (Livre)",
        descricao: "Ativa/desativa/opera 6 objetos (alcance médio) OU sobrecarrega objetos (Dano 2d12 Energia/objeto, Refl DT 30 metade).",
      },
      {
        nome: "MANIFESTAR O IMPOSSÍVEL (Completa)",
        descricao: "Invoca criaturas Energia (VD 240).",
      },
    ],
  },
  {
    id: "anomiatico",
    nome: "Anomiático",
    elemento: "Energia",
    vd: 240,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 30 • 6d8 mental • NEX 75%+ é imune)",
    foto: "/assets/bestiario/Anomiatico.webp",
    sentidos: "Percepção 40+10, Visão no escuro",
    iniciativa: "50+15",
    defesa: 41,
    fortitude: "30+10",
    reflexos: "50+20",
    vontade: "40+15",
    pv_max: 600,
    pv_atual: 600,
    machucado: 300,
    resistencias: "Balístico, corte e perfuração 10, Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 5, for: 3, int: 1, pre: 4, vig: 3 },
    deslocamento: "18m | 12q",
    habilidades: [
      "COMPORTAMENTO ERRÁTICO: 3x 1d6 - Ações aleatórias. Perde Resistência/Dano se falhar nas ações.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRA DESINTEGRADORA (C.C. x2) Teste 50+30 | Dano 4d12+20 Energia.",
      },
    ],
  },
  {
    id: "ciborgue",
    nome: "Ciborgue",
    elemento: "Energia",
    vd: 80,
    tipo: "Criatura Grande",
    presenca: "Perturbadora (DT 15 • 2d6 mental • NEX 40%+ é imune)",
    foto: "/assets/bestiario/Ciborgue.webp",
    sentidos: "Percepção 20+5, Visão no escuro",
    iniciativa: "20+10",
    defesa: 25,
    fortitude: "30+10",
    reflexos: "30+5",
    vontade: "2d20",
    pv_max: 160,
    pv_atual: 160,
    machucado: 80,
    imunidades: "Condições de paralisia",
    resistencias: "Balístico, corte e perfuração 10, Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 3, for: 4, int: 2, pre: 2, vig: 3 },
    deslocamento: "9m | 6q",
    habilidades: [
      "ENIGMA DE MEDO: Resolver fraqueza de cada estado (sofrer dano tipo/substância específica). Consequência: Desativação total.",
      "ESTADO DE COMBATE: Assume 1 de 4 estados/turno. Perde estado se fraqueza resolvida. Sem estados, Defesa 10/Deslocamento 0.",
      "REGENERAÇÃO ENERGÉTICA: Recupera 20 PV/turno. Perde se 3+ estados perdidos.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão) - Alpha",
        descricao: "BRAÇO LAMINADO (C.C. x2, crítico 18) Teste 30+10 | Dano 1d12+10 corte.",
      },
      {
        nome: "Agredir (Padrão) - Beta",
        descricao: "PUNHO ENERGIZADO (C.C.) Teste 30+10 | Dano 2d8+10 impacto.",
      },
      {
        nome: "INVESTIDA ENERGÉTICA (Completa) - Beta",
        descricao: "Avance 24m, ataque Punho (+O) | Dano +2d8. Derruba (Fort DT 20 evita).",
      },
      {
        nome: "Agredir (Padrão) - Gama",
        descricao: "CANHÃO (Distância - Longo) Teste 30+10 | Dano 4d12+5 Energia.",
      },
      {
        nome: "Agredir (Padrão) - Delta",
        descricao: "RAIO ENERGÉTICO (Distância - Médio) Teste 30d20+10 | Dano 1d12+5 Energia.",
      },
      {
        nome: "CRIAR BARREIRA (Movimento) - Delta",
        descricao: "+5 Defesa.",
      },
      {
        nome: "REINICIAR (Movimento) - Delta",
        descricao: "Encerra 1 condição.",
      },
      {
        nome: "DESORIENTAR (Livre) - Delta",
        descricao: "Dano Raio: alvo alquebrado. Alquebrado: atordoado 1 rodada (Vontade DT 20 evita).",
      },
    ],
  },
  {
    id: "infecticidio",
    nome: "Infecticídio",
    elemento: "Energia",
    vd: 280,
    tipo: "Criatura Enorme",
    presenca: "Perturbadora (DT 35 • 8d6 mental • NEX 85%+ é imune)",
    foto: "/assets/bestiario/Infecticidio.webp",
    sentidos: "Percepção +10, Visão no escuro",
    iniciativa: "3d20+15",
    defesa: 25,
    fortitude: "5d20+20",
    reflexos: "30+15",
    vontade: "1d20+15",
    pv_max: 600,
    pv_atual: 600,
    machucado: 300,
    resistencias: "Balístico, corte, perfuração e Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 3, for: 5, int: 1, pre: 1, vig: 5 },
    deslocamento: "9m | 6q",
    habilidades: [
      "HORDA: Sofre metade do dano de ataques 1 alvo. Sofre dobro de dano de área. Erro: causa metade do dano.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADAS INFECTADAS (C.C. x3) Teste 50+30 | Dano 4d12+20 Energia.",
      },
      {
        nome: "INFECÇÃO (Livre)",
        descricao: "Dano Pancada: infectado com vírus (Fort DT 30 evita).",
      },
      {
        nome: "CONSUMAÇÃO INSIDIOSA (Reação)",
        descricao: "Reduz a 0 PV: recupera 50 PV.",
      },
      {
        nome: "ATROPELAR (Completa)",
        descricao: "Desloca 2x, ataca cada alvo no caminho (Pancada Infectada).",
      },
    ],
  },
  {
    id: "perturbado_de_energia",
    nome: "Perturbado de Energia",
    elemento: "Energia",
    vd: 40,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 15 • 2d8 mental • NEX 30%+ é imune)",
    foto: "/assets/bestiario/Perturbado de Energia.webp",
    sentidos: "Percepção -2d20, Visão no escuro",
    iniciativa: "40+10",
    defesa: 19,
    fortitude: "-2d20",
    reflexos: "40+10",
    vontade: "-2d20",
    pv_max: 60,
    pv_atual: 60,
    machucado: 30,
    resistencias: "Balístico, corte e perfuração 5, Energia 10",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 4, for: 1, int: 0, pre: 0, vig: 0 },
    deslocamento: "9m | 6q",
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "TOQUE PLASMÁTICO (C.C. x2) Teste 40+10 | Dano 2d12 Energia.",
      },
      {
        nome: "IMPLANTAR CONFUSÃO (Livre)",
        descricao: "Dano Toque: agarra alvo (teste 4d+10). Agarrado: Dano 2d8 mental (Vontade DT 15 reduz à metade), vulnerável a Energia.",
      },
    ],
  },
  {
    id: "sukkalgir",
    nome: "Sukkalgir",
    elemento: "Energia",
    vd: 160,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 25 • 4d8 mental • NEX 55%+ é imune)",
    foto: "/assets/bestiario/Sukkalgir.webp",
    sentidos: "Percepção 30+10, Visão no escuro",
    iniciativa: "30+10",
    defesa: 34,
    fortitude: "20+5",
    reflexos: "30+10",
    vontade: "30+15",
    pv_max: 220,
    pv_atual: 220,
    machucado: 110,
    imunidades: "Dano balístico, de corte e de perfuração",
    resistencias: "Impacto e Energia 10",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 3, for: 2, int: 3, pre: 3, vig: 2 },
    deslocamento: "Voo 18m | 12q",
    habilidades: [
      "AURA DESESPERADA: Início do turno: Dano 2d12 mental em alcance curto (Vontade DT 25 reduz à metade).",
      "ESPÍRITO PLASMÁTICO: Atravessa obstáculos sólidos.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "MORDIDA DO OUTRO LADO (C.C. x2) Teste 30+15 | Dano 2d12 mental.",
      },
      {
        nome: "AGARRÃO (Livre)",
        descricao: "Acerto Mordida: agarra alvo (teste 30+15).",
      },
      {
        nome: "GRITO DE DESESPERO (Completa)",
        descricao: "Dano 3d12 mental (Vontade DT 20 reduz à metade).",
      },
    ],
  },
  {
    id: "telopsia",
    nome: "Telopsia",
    elemento: "Energia",
    vd: 340,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 40 • 10d6 mental • NEX 99%+ é imune)",
    foto: "/assets/bestiario/Telopsia.webp",
    sentidos: "Percepção 50+25, Visão no escuro",
    iniciativa: "40+20",
    defesa: 48,
    fortitude: "20+15",
    reflexos: "40+20",
    vontade: "50+25",
    pv_max: 560,
    pv_atual: 560,
    machucado: 280,
    imunidades: "Condições de paralisia",
    resistencias: "Balístico, corte, perfuração e Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 4, for: 2, int: 3, pre: 5, vig: 2 },
    deslocamento: "12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Destruir fita amaldiçoada. Consequência: PV reduzidos a 0.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "TOQUE DESINTEGRADOR (C.C. x3) Teste 40+35 | Dano 6d12+30 Energia.",
      },
      {
        nome: "VIAJAR PELA TELA (Movimento)",
        descricao: "Teletransporte para tela/visor (alcance longo), desloca 9m.",
      },
      {
        nome: "TELA ZUMBIFICADORA (Padrão)",
        descricao: "Dano 6d6 mental, confuso (Vontade DT 30 reduz à metade/evita). Confuso + Falha: fascinado.",
      },
      {
        nome: "PRENDER NA TELA (Completa)",
        descricao: "Alvo em alcance curto: preso na tela (Fort DT 30 evita). Preso: paralisado, Dano 2d12 mental/turno.",
      },
    ],
  },
  {
    id: "tempestuoso",
    nome: "Tempestuoso",
    elemento: "Energia",
    vd: 360,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 40 • 8d8 mental)",
    foto: "/assets/bestiario/Tempestuoso.webp",
    sentidos: "Percepção 50+20, Visão no escuro",
    iniciativa: "40+25",
    defesa: 56,
    fortitude: "4d20+20",
    reflexos: "5d20+30",
    vontade: "50+25",
    pv_max: 950,
    pv_atual: 950,
    machucado: 475,
    imunidades: "Condições de paralisia",
    resistencias: "Balístico, corte, perfuração e Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 5, for: 4, int: 2, pre: 5, vig: 4 },
    deslocamento: "24m | 12q",
    habilidades: [
      "AURA RADIOATIVA: Início do turno: Dano 2d20+20 Energia em alcance curto (Fort DT 40 reduz à metade).",
      "ESPECTRO RADIOATIVO: Ataques C.C. alcançam Curto.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "GARRAS RADIOATIVAS (C.C. x2, Alcance Curto) Teste 50+40 | Dano 4d20+20 Energia.",
      },
      {
        nome: "RAIO DE ENERGIA RADIOATIVA (Livre)",
        descricao: "2 acertos Garras: dispara raio (Dano 4d20+20 Energia, Refl DT 40 reduz à metade).",
      },
      {
        nome: "EXPANDIR EM RADIAÇÃO (Completa)",
        descricao: "Dano 10d20+20 Energia (Refl DT 40 reduz à metade). Perde 100 PV.",
      },
    ],
  },
  {
    id: "viajante",
    nome: "Viajante",
    elemento: "Energia",
    vd: 200,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 20 • 6d6 mental • NEX 60%)",
    foto: "/assets/bestiario/Viajante.webp",
    sentidos: "Percepção 40+15, Visão no escuro",
    iniciativa: "40+15",
    defesa: 34,
    fortitude: "20+10",
    reflexos: "40+15",
    vontade: "40+15",
    pv_max: 360,
    pv_atual: 360,
    machucado: 180,
    resistencias: "Balístico, corte e perfuração 10, Energia 20",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 4, for: 2, int: 3, pre: 4, vig: 2 },
    deslocamento: "9m | 6q",
    habilidades: [
      "ENIGMA DE MEDO: Fotografar. Consequência: Perde Invisibilidade Permanente por 1 turno.",
      "INVISIBILIDADE PERMANENTE: Invisível, +15 Furtividade, alvo desprevenido.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (C.C. x2) Teste 4d20+15 | Dano 2d12+10 impacto.",
      },
      {
        nome: "AGARRÃO (Livre)",
        descricao: "Acerto Pancada: agarra alvo (teste 40+15).",
      },
      {
        nome: "DEVORAR MEMÓRIA (Completa)",
        descricao: "Alvo agarrado: Dano 4d12 mental, esquece 1 pessoa (Vontade DT 29 reduz à metade/evita efeito). Perturbado: +1d12 dano Pancada.",
      },
    ],
  },
  {
    id: "o_anfitriao",
    nome: "O Anfitrião",
    elemento: "Energia",
    vd: 400,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 45 • 10d8 mental)",
    foto: "/assets/bestiario/o_anfitriao.webp",
    sentidos: "Percepção 6d20+25, Visão no escuro",
    iniciativa: "7d20+35",
    defesa: 59,
    fortitude: "5d20+25",
    reflexos: "7d20+35",
    vontade: "6d20+25",
    pv_max: 1413,
    pv_atual: 1413,
    machucado: 706,
    imunidades: "Condições de paralisia, dano, dano e efeitos de Energia",
    vulnerabilidades: "Conhecimento",
    atributos: { agi: 7, for: 5, int: 6, pre: 6, vig: 5 },
    deslocamento: "12m | 8q",
    habilidades: [
      "ENIGMA DE MEDO: Confrontar sob proteção da Máscara do Desespero.",
      "POTÊNCIA DE ENERGIA: Modificador +35 (AGI, INT), +25 (FOR, PRE, VIG).",
      "ATO 1: Divide-se em 5 facetas (Amphitruo, Aeneas, Liber, Silenus e Plautus). Cada uma com 250 PV, RD 20. Usam habilidades de seu nome. Reúne-se no Ato 2.",
      "ATO 2: Forma única, 3 ações padrão/rodada diferentes. Ganha todas as habilidades das facetas. Trilha Sonora (Dano 2d10 mental/turno) e Roleta Maluca (efeitos aleatórios).",
    ],
    acoes: [
      // Habilidades do Ato 2 (e Facetas):
      {
        nome: "TEATRO (Padrão) - Amphitruo",
        descricao: "Alvo recita texto ou sofre 10d6 mental (Artes DT 35 ou Vontade DT 45 evita).",
      },
      {
        nome: "QUEIMAR (Padrão) - Aeneas",
        descricao: "Dano 10d6+20 Energia (Reflexos DT 45 reduz à metade).",
      },
      {
        nome: "CORTE CAÓTICO (Padrão) - Liber",
        descricao: "C.C. Teste 7O+45 | Dano 3d12+20 Energia. Livre: ROMANCE FORÇADO (alvos decidem quem sofre o dano).",
      },
      {
        nome: "LANÇA E ADAGA (Padrão) - Plautus",
        descricao: "C.C. x2. Teste 7O+45 | Dano 2d12+20 Energia. Livre: EU SOU O CAOS (+4d12 Energia se alvo desprevenido/flanqueado).",
      },
      {
        nome: "CORTE DE ÁGUA (Padrão) - Silenus",
        descricao: "C.C. Dano 5d12+20 Energia. Livre: AFOGAMENTO (alvo asfixiado, Fort DT 35 evita).",
      },
      {
        nome: "TELETRANSPORTE (Movimento)",
        descricao: "Teletransporte alcance médio.",
      },
    ],
  },
  // --- CRIATURAS DE MEDO E VARIAÇÕES ---
  {
    id: "degolificada",
    nome: "Degolificada",
    elemento: "Medo",
    vd: 320,
    tipo: "Criatura Médio",
    presenca: "Perturbadora (DT 40 • 9d6 mental • NEX 95%+ é imune)",
    foto: "/assets/bestiario/Degolificada.webp",
    sentidos: "Percepção 4d20+15, Percepção às cegas",
    iniciativa: "3d20",
    defesa: 45,
    fortitude: "4d20+20",
    reflexos: "3d20+15",
    vontade: "4d20+25",
    pv_max: 850,
    pv_atual: 850,
    machucado: 425,
    imunidades: "Dano (removida se Enigma resolvido)",
    atributos: { agi: 3, for: 5, int: 3, pre: 4, vig: 4 },
    deslocamento: "6m | 4q",
    habilidades: [
      "ENIGMA DE MEDO: Confrontar com a causa da morte. Consequência: Perde Imunidade a Dano.",
      "CRIATURA DO MEDO: Imune a dano até Enigma resolvido.",
      "MECÂNICA ESPECIAL: METAMORFOSE: 4 formas elementais com gatilhos e habilidades específicas.",
    ],
    acoes: [
      {
        nome: "Agredir (Padrão)",
        descricao: "PANCADA (C.C. x2) Teste 5d20+35 | Dano 8d8+20 impacto.",
      },
      {
        nome: "AGARRAR E ESTRANGULAR (Livre)",
        descricao: "Acerto Pancada: agarra (teste 5d20+35), asfixiado. Mantém 2 alvos.",
      },
      {
        nome: "GRITO RASGADO (Livre)",
        descricao: "1x/cena. Dano 4d10+10 mental + 1d4 efeitos de surdez (Vontade DT 35 reduz à metade/evita).",
      },
      {
        nome: "DESFIGURAMENTO CAPILAR (Movimento)",
        descricao: "Alvo agarrado: Dano 10d6+20 perfuração, Dano 6d10 mental (Fort/Von DT 35 reduz à metade).",
      },
    ],
  },
];