const SUPPLEMENT_BOOKS = Object.freeze({
  sah: {
    id: 'sah',
    nome: 'Sobrevivendo ao Horror',
    sigla: 'SaH',
    edicao: 'v1.1',
  },
  as1: {
    id: 'as1',
    nome: 'Arquivos Secretos #1',
    sigla: 'AS #1',
  },
  as2: {
    id: 'as2',
    nome: 'Arquivos Secretos #2',
    sigla: 'AS #2',
  },
  as3: {
    id: 'as3',
    nome: 'Arquivos Secretos #3',
    sigla: 'AS #3',
  },
  as4: {
    id: 'as4',
    nome: 'Arquivos Secretos #4',
    sigla: 'AS #4',
  },
});

function comFonte(conteudo, livro, pagina) {
  const fonte = SUPPLEMENT_BOOKS[livro];
  return {
    ...conteudo,
    fonte: {
      livro,
      nome: fonte.nome,
      sigla: fonte.sigla,
      pagina,
    },
  };
}

const SUPPLEMENT_ORIGINS = {
  ferido_por_ritual: comFonte({
    nome: 'Ferido por Ritual',
    fixas: ['ocultismo'],
    escolhas: [{
      titulo: 'Perícia do elemento',
      descricao: 'Escolha Fortitude para Sangue, Vontade para Morte ou Conhecimento, ou Reflexos para Energia.',
      grupo: 'elementoRitual',
      opcoes: ['fortitude', 'vontade', 'reflexos'],
      opcoesPorNarrativa: {
        Sangue: ['fortitude'],
        Morte: ['vontade'],
        Conhecimento: ['vontade'],
        Energia: ['reflexos'],
      },
      quantidade: 1,
    }],
    opcoesNarrativas: [{
      key: 'elemento_ritual',
      titulo: 'Elemento da mácula',
      descricao: 'A mácula, o ritual aprendido e a vulnerabilidade da origem usam este elemento.',
      opcoes: [
        { value: 'Sangue', label: 'Sangue' },
        { value: 'Morte', label: 'Morte' },
        { value: 'Conhecimento', label: 'Conhecimento' },
        { value: 'Energia', label: 'Energia' },
      ],
    }],
    poder: {
      nome: 'Mácula Ritualística',
      descricao: 'Aprende um ritual de 1º círculo do elemento escolhido, fora do limite de rituais. Uma vez por cena pode conjurá-lo sem o custo básico de PE, mas sofre -1d20 em testes de resistência contra efeitos desse elemento.',
    },
  }, 'as1', 43),
  transtornado_arrependido: comFonte({
    nome: 'Transtornado Arrependido',
    fixas: ['luta', 'ocultismo'],
    poder: {
      nome: 'Sofrimento de Sangue',
      descricao: 'Recebe RD 2 mental, aumentada em +1 para cada dois rituais ou poderes paranormais de Sangue. A condição de descanso é sempre uma categoria pior.',
    },
  }, 'as1', 43),
  cacador_recompensas: comFonte({
    nome: 'Caçador de Recompensas',
    fixas: ['crime', 'investigacao'],
    poder: {
      nome: 'Quem Não Arrisca, Não Petisca',
      descricao: 'Recebe +2 em testes para resistir a condições mentais e de medo. Ao falhar em um desses testes, recebe +1d20 no próximo teste feito até o fim da cena.',
    },
  }, 'as4', 64),
  influencer_paranormal: comFonte({
    nome: 'Influencer Paranormal',
    fixas: ['enganacao', 'tecnologia'],
    poder: {
      nome: 'Registrar o Paranormal',
      descricao: 'Uma vez por cena, registra uma criatura ou ritual por 2 PE. Recebe +5 contra a presença perturbadora de criaturas já registradas e pode memorizar um ritual registrado durante um interlúdio até o próximo interlúdio.',
    },
  }, 'as4', 64),
};

const SUPPLEMENT_POWERS = {
  combatente: [
    comFonte({
      key: 'guardiao_tropa',
      nome: 'Guardião da Tropa',
      tipo: 'Combate',
      prerequisito: 'Ataque Especial, Casca Grossa',
      descricao: 'Quando um aliado adjacente for o único alvo de um ataque ou habilidade, gaste uma reação e 2 PE para receber o efeito no lugar dele. Se o efeito não superar sua Defesa ou for completamente resistido, recupere 1 SAN. Pode ser escolhido novamente para alcance curto.',
    }, 'as3', 108),
    comFonte({
      key: 'vitalidade_sofrida',
      nome: 'Vitalidade Sofrida',
      tipo: 'Geral',
      prerequisito: 'Ataque Especial',
      descricao: 'Altera a progressão do combatente para 24 + Vigor PV iniciais, 6 + Vigor PV por nível, 11 SAN iniciais e 2 SAN por nível. Aplica-se retroativamente.',
    }, 'as3', 108),
    comFonte({
      key: 'chuva_balas',
      nome: 'Chuva de Balas',
      tipo: 'Combate',
      prerequisito: null,
      descricao: 'Dobra a duração por cena dos pacotes de munição. Antes do dano de uma arma de fogo, pode consumir pacotes inteiros para causar +2 dados do mesmo tipo por pacote. Com contagem de munição, cada pacote recebe +10 balas.',
    }, 'as4', 65),
    comFonte({
      key: 'combatente_esforcado',
      nome: 'Combatente Esforçado',
      tipo: 'Geral',
      prerequisito: 'For 3 ou Vig 3',
      descricao: 'Recebe +1 PE para cada nível de NEX.',
    }, 'as4', 65),
    comFonte({
      key: 'treinamento_militarizado',
      nome: 'Treinamento Militarizado',
      tipo: 'Perícia',
      prerequisito: null,
      descricao: 'O bônus de exercitar-se em um interlúdio passa a +1d8 e também pode ser gasto em rolagens de dano, limitado a um bônus por rolagem.',
    }, 'as4', 65),
  ],
  especialista: [
    comFonte({
      key: 'analise_conturbada',
      nome: 'Análise Conturbada',
      tipo: 'Investigação',
      prerequisito: null,
      descricao: 'Em uma investigação, gaste uma ação padrão para expor análises sombrias. Participantes voluntários rolam 1d6, recebem o resultado como bônus em testes de Intelecto e Presença até o fim da cena e perdem a mesma quantidade de SAN.',
    }, 'as4', 65),
    comFonte({
      key: 'profissao_perigo',
      nome: 'Profissão Perigo',
      tipo: 'Perícia',
      prerequisito: null,
      descricao: 'Uma vez por missão, gaste uma ação completa e 4 PE para desmontar um item e criar um item operacional que não ultrapasse sua categoria nem seus espaços.',
    }, 'as4', 65),
    comFonte({
      key: 'quase_novo',
      nome: 'Quase Novo',
      tipo: 'Perícia',
      prerequisito: null,
      descricao: 'Ao fazer manutenção, o item reparado recebe +10 PV e pode ganhar uma modificação temporária acessível até o próximo interlúdio.',
    }, 'as4', 65),
  ],
  ocultista: [
    comFonte({
      key: 'ritual_intenso',
      nome: 'Ritual Intenso',
      tipo: 'Ritual',
      prerequisito: 'Pre 2',
      descricao: 'Soma Presença às rolagens de dano e cura dos seus rituais.',
    }, 'as1', 44),
    comFonte({
      key: 'saude_sobrenatural',
      nome: 'Saúde Sobrenatural',
      tipo: 'Ritual',
      prerequisito: 'Int 2, Pre 2, conjurar ritual de 1º círculo',
      descricao: 'Uma vez por cena, gaste uma ação de movimento e 3 PE para receber Presença x 10 PV temporários até o fim da cena. Não acumula consigo mesmo.',
    }, 'as1', 44),
    comFonte({
      key: 'acostumado_maldicao_elemento',
      nome: 'Acostumado a Maldição de Elemento',
      tipo: 'Paranormal',
      prerequisito: 'Int 2, conjurar ritual de 2º círculo do elemento escolhido',
      requiresChoice: 'elemento',
      descricao: 'Escolha Sangue, Morte, Conhecimento ou Energia. Ao falhar no preço da maldição de um item desse elemento, não perde SAN, mas ainda sofre os demais efeitos.',
    }, 'as1', 44),
    comFonte({
      key: 'reter_ritual_combate',
      nome: 'Reter Ritual de Combate',
      tipo: 'Ritual',
      prerequisito: 'Int 2, conjurar ritual de 1º círculo e usar a regra Reter Ritual',
      descricao: 'Como reação, transforma em cena um ritual retido que deixaria de afetar um alvo fora da linha de efeito. Ao perder o foco, pode pagar 1 PE por ritual para mudar sua duração para cena.',
    }, 'as1', 44),
    comFonte({
      key: 'flagelo_bem_aproveitado',
      nome: 'Flagelo Bem Aproveitado',
      tipo: 'Ritual',
      prerequisito: 'Escolhido pelo Outro Lado, Recuperação Flagelante',
      descricao: 'A taxa da habilidade Poder do Flagelo passa a 1 PV por 1 PE pago.',
    }, 'as3', 108),
    comFonte({
      key: 'recuperacao_flagelante',
      nome: 'Recuperação Flagelante',
      tipo: 'Ritual',
      prerequisito: 'Escolhido pelo Outro Lado, Poder do Flagelo',
      descricao: 'Entre interlúdios, permite recuperar uma vez por outros métodos os PV gastos com Poder do Flagelo. Pode ser escolhido novamente até três usos.',
    }, 'as3', 108),
    comFonte({
      key: 'explorador_nevoa',
      nome: 'Explorador da Névoa',
      tipo: 'Paranormal',
      prerequisito: null,
      descricao: 'Uma vez por cena, gaste 2 PE para identificar o estado da Membrana. Se estiver danificada ou pior, perca 1 SAN e reduza em 1 PE o custo de todos os seus rituais na cena.',
    }, 'as4', 66),
    comFonte({
      key: 'sinestesia_paranormal',
      nome: 'Sinestesia Paranormal',
      tipo: 'Paranormal',
      prerequisito: null,
      descricao: 'Ao entrar em uma área com Membrana danificada ou pior, pode perder 1d6 SAN para trocar entre si os atributos-base de dois pares de perícias até deixar a área. Só pode aceitar novamente no dia seguinte.',
    }, 'as4', 66),
    comFonte({
      key: 'terrores_noturnos',
      nome: 'Terrores Noturnos',
      tipo: 'Paranormal',
      prerequisito: null,
      descricao: 'Ao dormir, role 1d100. Em 50 ou menos, o descanso vira precário e você perde 1d4 SAN, mas pode usar uma vez até o próximo interlúdio um poder paranormal ou ritual cujos pré-requisitos cumpra.',
    }, 'as4', 66),
  ],
  gerais: [
    comFonte({
      key: 'habilidade_aprimorada',
      nome: 'Habilidade Aprimorada',
      tipo: 'Geral',
      prerequisito: null,
      descricao: 'Escolha uma habilidade ou ritual com DT. A DT aumenta em +2. Pode ser escolhido novamente para opções diferentes ou até duas vezes para a mesma opção; nesse caso o aumento total é +5.',
    }, 'as1', 46),
    comFonte({
      key: 'instintos_urbanos',
      nome: 'Instintos Urbanos',
      tipo: 'Perícia',
      prerequisito: 'Agi 2',
      descricao: 'Recebe treinamento em Crime ou +2 se já for treinado. Ao entrar em ambiente fechado, Crime DT 20 identifica uma rota de fuga, fornecendo uma ação de movimento extra no primeiro turno da fuga e +2 Defesa até escapar.',
    }, 'as1', 46),
    comFonte({
      key: 'cicatrizes_expostas',
      nome: 'Cicatrizes Expostas',
      tipo: 'Combate',
      prerequisito: 'Ter cicatrizes',
      descricao: 'Gaste uma ação de movimento para expor suas cicatrizes até o fim da cena: causa +1d8 de dano do mesmo tipo, mas sofre -1d20 em Vontade e ações que exijam calma.',
    }, 'as1', 46),
    comFonte({
      key: 'curiosidade_oculta',
      nome: 'Curiosidade Oculta',
      tipo: 'Perícia',
      prerequisito: 'Int 2',
      descricao: 'Recebe treinamento em Ocultismo ou +2 se já for treinado. Em testes de Vontade, pode gastar 2 PE para usar Ocultismo no lugar.',
    }, 'as1', 46),
    comFonte({
      key: 'especialista_exoterico',
      nome: 'Especialista Exotérico',
      tipo: 'Ritual',
      prerequisito: 'Int 3, 2º círculo, Domínio Esotérico',
      descricao: 'Ao conjurar um ritual, combina simultaneamente os efeitos de até três catalisadores ritualísticos diferentes.',
    }, 'as1', 46),
    comFonte({
      key: 'ambidestria',
      nome: 'Ambidestria',
      tipo: 'Combate',
      prerequisito: 'For 2 ou Agi 2, treinado em Luta',
      descricao: 'Permite atacar com duas armas, sendo ao menos uma leve, sofrendo -1d20 nos ataques até o próximo turno. Com Combater com Duas Armas, elimina a penalidade e permite duas armas de uma mão.',
    }, 'as3', 108),
    comFonte({
      key: 'entrada_triunfal',
      nome: 'Entrada Triunfal',
      tipo: 'Perícia',
      prerequisito: 'Pre 2',
      descricao: 'Uma vez por sessão, ao anunciar sua entrada em um ambiente, recebe +2d20 no primeiro teste feito ali, exceto Furtividade, ou transfere o bônus por reação ao primeiro teste de um aliado em alcance longo.',
    }, 'as3', 109),
    comFonte({
      key: 'papinho_sedutor',
      nome: 'Papinho Sedutor',
      tipo: 'Perícia',
      prerequisito: 'Pre 2',
      descricao: 'Ao seduzir com uma perícia de Presença, gaste 1 PE para receber +5. Se passar, o alvo fica apaixonado, com possíveis complicações narrativas definidas pelo mestre.',
    }, 'as3', 109),
    comFonte({
      key: 'causar_culpa',
      nome: 'Causar Culpa',
      tipo: 'Sacrifício',
      prerequisito: 'Ser o sacrifício da Culpa',
      descricao: 'Ação padrão e 3 PE: uma pessoa em alcance curto faz Vontade contra DT Pre +5. Se falhar, fica indefesa e repete o teste no início de cada turno.',
    }, 'as3', 110),
    comFonte({
      key: 'despertar_obsessao',
      nome: 'Despertar Obsessão',
      tipo: 'Sacrifício',
      prerequisito: 'Ser o sacrifício da Obsessão',
      descricao: 'Ação padrão e 3 PE: o alvo desvia o olhar e fica desprevenido por uma rodada, ou encara e testa Vontade contra DT Pre +5; se falhar, deve adorar você ou se atacar.',
    }, 'as3', 110),
    comFonte({
      key: 'arrogancia_diabolica',
      nome: 'Arrogância Diabólica',
      tipo: 'Sacrifício',
      prerequisito: 'Ser o sacrifício do Orgulho',
      descricao: 'Ação padrão e 3 PE: uma pessoa em alcance médio testa Vontade contra DT Pre -5. Se falhar, faz uma ação extremamente imprudente; se passar, sofre 2d6 dano mental irredutível.',
    }, 'as3', 110),
    comFonte({
      key: 'estimular_hedonismo',
      nome: 'Estimular Hedonismo',
      tipo: 'Sacrifício',
      prerequisito: 'Ser o sacrifício do Prazer',
      descricao: 'Ação padrão e 3 PE: uma pessoa em alcance curto testa Vontade contra DT Pre +5. Se falhar, fica indefesa por uma rodada e só busca prazer imediato.',
    }, 'as3', 111),
    comFonte({
      key: 'fruto_ambicao',
      nome: 'Fruto da Ambição',
      tipo: 'Sacrifício',
      prerequisito: 'Ser o sacrifício do Desejo',
      descricao: 'Escolha um poder ou ritual conhecido como gatilho de uma forma suprema pelas regras de Máscaras. Se já possuir uma máscara, aprende um ritual de Sangue de 4º círculo.',
    }, 'as3', 111),
    comFonte({
      key: 'odio_suprimido',
      nome: 'Ódio Suprimido',
      tipo: 'Sacrifício',
      prerequisito: 'Ser o sacrifício do Rancor',
      descricao: 'Ação completa e 3 PE: seres em alcance curto fazem Fortitude e Reflexos contra DT Pre +5. Falhas sofrem seu dano corpo a corpo e/ou à distância. Depois, você fica exausto até o fim da cena.',
    }, 'as3', 111),
    comFonte({
      key: 'gororoba',
      nome: 'Gororoba',
      tipo: 'Interlúdio',
      prerequisito: null,
      descricao: 'Em uma cena de interlúdio, pode alimentar-se uma vez sem gastar ação nem precisar de uma refeição disponível.',
    }, 'as4', 66),
    comFonte({
      key: 'ruido_branco',
      nome: 'Ruído Branco',
      tipo: 'Perícia',
      prerequisito: null,
      descricao: 'Em ambientes movimentados ou com conversas paralelas, recebe +1d6 em Investigação e Percepção. Uma vez por cena, pode gastar 1 PE para obter uma informação útil entre as vozes, a critério do mestre.',
    }, 'as4', 66),
    comFonte({
      key: 'ultima_olhada',
      nome: 'Uma Última Olhada',
      tipo: 'Investigação',
      prerequisito: null,
      descricao: 'Uma vez por cena, na última rodada de uma investigação, gaste 2 PE para aumentar a urgência em +1 rodada para o grupo.',
    }, 'as4', 67),
  ],
  paranormais: [
    comFonte({
      key: 'ferro_maculado',
      nome: 'Ferro Maculado',
      tipo: 'Paranormal',
      elemento: 'Sangue',
      prerequisito: null,
      descricao: 'Ação de movimento e 2 PV amaldiçoam um projétil para causar +1d6 de Sangue uma vez. Afinidade: +1d8.',
    }, 'as1', 47),
    comFonte({
      key: 'placas_sanguinolentas',
      nome: 'Placas Sanguinolentas',
      tipo: 'Paranormal',
      elemento: 'Sangue',
      prerequisito: 'Conjurar ritual de Sangue',
      descricao: 'Ao conjurar ritual de Sangue, recebe Defesa igual ao círculo até o início do próximo turno. Afinidade: círculo +2.',
    }, 'as1', 47),
    comFonte({
      key: 'sangue_corrosivo',
      nome: 'Sangue Corrosivo',
      tipo: 'Paranormal',
      elemento: 'Sangue',
      prerequisito: null,
      descricao: 'Ação de movimento e 1 PE tornam seu sangue corrosivo na cena. Ao sofrer dano de um ser adjacente, causa 1d10 de Sangue nele. Afinidade: 2d10.',
    }, 'as1', 47),
    comFonte({
      key: 'sangue_prazeroso',
      nome: 'Sangue Prazeroso',
      tipo: 'Paranormal',
      elemento: 'Sangue',
      prerequisito: 'Sangue 1',
      descricao: 'Enquanto machucado, recebe RD 5. Afinidade: também recebe 20 PV temporários uma vez por cena.',
    }, 'as1', 47),
    comFonte({
      key: 'intencao_prove_se_digno',
      nome: 'Prove-se Digno',
      tipo: 'Intenção',
      elemento: 'Intenção',
      prerequisito: 'Contato com a Coroa de Espinhos',
      descricao: 'Gatilho: obedecer à vontade d’Ele. Na mesma cena, uma vez, use uma reação para transformar um teste em sucesso automático, como um 20 natural.',
    }, 'as2', 94),
    comFonte({
      key: 'intencao_dor_amiga',
      nome: 'A Dor Tornou-se Amiga',
      tipo: 'Intenção',
      elemento: 'Intenção',
      prerequisito: 'Contato com a Coroa de Espinhos',
      descricao: 'Gatilho: sofrer três ferimentos de pelo menos 5 de dano. Reação: recebe RD 25, mas perde 5 PV no início dos turnos até desativar por reação.',
    }, 'as2', 95),
    comFonte({
      key: 'intencao_materia_prima_mortos',
      nome: 'Intenção dos Mortos',
      tipo: 'Intenção',
      elemento: 'Intenção',
      prerequisito: 'Contato com a Coroa de Espinhos',
      descricao: 'Gatilho: testemunhar a morte de uma pessoa. Ação padrão: absorve a intenção de um cadáver em alcance curto e cura um ser em alcance curto em metade dos PV máximos do cadáver.',
    }, 'as2', 95),
    comFonte({
      key: 'intencao_silencio_assombra',
      nome: 'O Silêncio Assombra',
      tipo: 'Intenção',
      elemento: 'Intenção',
      prerequisito: 'Contato com a Coroa de Espinhos',
      descricao: 'Gatilho: provar o sangue de um ser adjacente machucado com uma ação padrão. Na cena, ataques causam +1d8 e +2 margem; críticos silenciam o alvo por 1d4 rodadas.',
    }, 'as2', 95),
    comFonte({
      key: 'intencao_fazer_pagar',
      nome: 'Faça os Responsáveis Pagarem',
      tipo: 'Intenção',
      elemento: 'Intenção',
      prerequisito: 'Contato com a Coroa de Espinhos',
      descricao: 'Gatilho: perceber um aliado que tentou proteger ficando morrendo. Como reação, ataca quem o derrubou; também pode reagir antes de cair inconsciente contra quem deixou você morrendo.',
    }, 'as2', 95),
    comFonte({
      key: 'instrumento_eletrico_combate',
      nome: 'Instrumento Elétrico de Combate',
      tipo: 'Paranormal',
      elemento: 'Energia',
      prerequisito: null,
      descricao: 'Transforma um instrumento musical em arma tática amaldiçoada de duas mãos: ataque à distância com Artes, 2d8 Energia + Presença, alcance curto, crítico 20/x2, categoria II e 2 espaços. Afinidade: atinge todos os alvos escolhidos em alcance curto.',
    }, 'as3', 109),
    comFonte({
      key: 'direcao_precognitiva',
      nome: 'Conhecimento de Direção Precognitiva',
      tipo: 'Paranormal',
      elemento: 'Conhecimento',
      prerequisito: null,
      descricao: 'Recebe +5 em Percepção ou Sobrevivência para localização e orientação até um local desconhecido. Afinidade: +10.',
    }, 'as3', 109),
    comFonte({
      key: 'foco_gravitacional',
      nome: 'Foco Gravitacional',
      tipo: 'Paranormal',
      elemento: 'Energia',
      prerequisito: null,
      descricao: 'Um equipamento ocupa 0 espaços guardado, mas ao ser empunhado tem 25% de chance de voar para um espaço em alcance curto escolhido pelo mestre. Afinidade: até três equipamentos.',
    }, 'as4', 67),
    comFonte({
      key: 'sobrepor_imprevisivel',
      nome: 'Sobrepor Imprevisível',
      tipo: 'Paranormal',
      elemento: 'Energia',
      prerequisito: null,
      descricao: 'Uma vez por rodada, no início dela, gaste 2 PE e role 1d20: resultado par é somado à iniciativa; ímpar é subtraído. Afinidade: role 2d20 e escolha.',
    }, 'as4', 67),
    comFonte({
      key: 'traco_inconsistencia',
      nome: 'Traço de Inconsistência',
      tipo: 'Paranormal',
      elemento: 'Energia',
      prerequisito: null,
      descricao: 'Como reação e por 2 PE, distorce sua identidade em imagens digitais no momento da captura. Afinidade: nunca pode ser captado em imagens digitais e sua voz fica distorcida em gravações.',
    }, 'as4', 67),
  ],
};

const SUPPLEMENT_TRAILS = {
  maledictologo: comFonte({
    nome: 'Maledictólogo',
    classe: 'ocultista',
    escala: 'NEX',
    habilidades: {
      10: 'Identificação Macabra (1 PE para +1d10 ao identificar item amaldiçoado ou ritual; apenas -1d20 para identificar item como ação completa)',
      40: 'Compreensão de Maldições (interlúdio e 3 PE para estudar, consumir e extrair ritual ou transferir maldições de um item)',
      65: 'Reproduzir Maldição (memoriza uma maldição e pode aplicá-la temporariamente a outro item, com custo de PE, teste de Ocultismo e perda de SAN)',
      99: 'Maldição Suprema (ao reproduzir uma maldição, considera o item três categorias efetivas abaixo)',
    },
  }, 'as1', 45),
  performatico: comFonte({
    nome: 'Performático',
    classe: 'geral',
    classes: ['combatente', 'especialista', 'ocultista'],
    escala: 'NEX',
    habilidades: {
      10: 'Ensaio (nova ação de interlúdio; aumenta a margem de ameaça até o próximo interlúdio e pode beneficiar aliados que ensaiem junto)',
      40: 'Frase de Efeito (2 PE ao ocorrer crítico em alcance curto para aumentar o multiplicador)',
      65: 'Mosh Pit (aliados cercando o mesmo alvo acumulam dados extras de dano, até +5d6)',
      99: 'Ritmo Contagiante (+5 Defesa para a equipe no início do combate, crescendo com seus críticos até +10)',
    },
  }, 'as3', 119),
  granadeiro_blaster: comFonte({
    nome: 'Granadeiro Blaster',
    classe: 'especialista',
    escala: 'NEX',
    habilidades: {
      10: 'Meus Bebês (treinamento ou +5 em Profissão químico; recebe explosivos autorais fora do limite de itens)',
      40: 'Fogo Amigo (recebe ou aprimora Perito em Explosivos e aumenta áreas de explosão em 6m)',
      65: 'O Calor do Momento (ação completa e 4 PE para fabricar explosivo autoral apressado, com 25% de risco)',
      99: 'Memória Muscular (explosivos autorais ficam mais rápidos de usar e causam o dobro de dados de dano)',
    },
  }, 'as4', 69),
};

const SUPPLEMENT_RITUALS = [
  comFonte({
    id: 'passagem_conhecimento',
    nome: 'Passagem de Conhecimento',
    elemento: 'Conhecimento',
    elementos: ['Sangue', 'Conhecimento'],
    circulo: 2,
    execucao: 'Completa',
    alcance: 'Toque',
    alvo: '1 pessoa',
    duracao: 'Cena',
    resistencia: 'Vontade evita',
    descricao: 'Transfere sua consciência ao corpo do alvo. Escolha habitar e tentar sobrepor a mente dele ou trocar completamente as consciências. A ficha é mantida, mas os atributos físicos passam a ser os do corpo ocupado.',
    discente: '+3 PE: alcance curto e duração de 1 dia. O alvo tenta retomar o controle apenas uma vez por dia ou cena. Requer 2º círculo.',
    verdadeiro: '+7 PE: alcance médio e duração permanente. A retomada do controle ocorre apenas uma vez por ano. Requer 4º círculo e afinidade.',
  }, 'as1', 48),
  comFonte({
    id: 'passagem_conhecimento_expandido',
    nome: 'Passagem de Conhecimento Expandido',
    elemento: 'Conhecimento',
    elementos: ['Sangue', 'Conhecimento'],
    circulo: 4,
    execucao: '1 dia',
    alcance: 'Curto',
    alvo: '2 a 10 pessoas, em número par',
    duracao: 'Permanente',
    resistencia: '',
    descricao: 'Versão coletiva da Passagem de Conhecimento. Divide os participantes em dois grupos e troca consciências conforme intenções e palavras-chave; nesta versão, atributos e habilidades do novo corpo são assumidos. Corpos transitórios abertos cedo podem originar um Anulado.',
  }, 'as1', 50),
  comFonte({
    id: 'backup',
    nome: 'Backup',
    elemento: 'Energia',
    circulo: 2,
    execucao: 'Padrão',
    alcance: 'Curto',
    alvo: 'Veja texto',
    duracao: '24 horas',
    resistencia: '',
    descricao: 'Cria um chamariz com sua aparência, movimentos simples e uma frase. Dentro de 50 km, use uma reação para trocar de lugar com ele e perder 2d4 SAN. Dano na cópia ou sair da área encerra o ritual.',
    discente: '+2 PE: duração permanente e permite alternar visão e audição com a cópia, ficando cego, surdo e pasmo enquanto usa seus sentidos.',
    verdadeiro: '+5 PE: como discente; permite falar e escolher outra aparência. Ao trocar, pode dissipar para causar 6d6 Energia em alcance curto nos dois pontos. Requer 3º círculo.',
  }, 'as4', 68),
];

const SUPPLEMENT_ITEMS = {
  armasTaticas: [
    comFonte({
      id: 'garra_harpia',
      nome: 'Garra do Harpia',
      categoria: 2,
      dano: '2d8',
      critico: '19/x2',
      alcance: 'Curto',
      tipo: 'C',
      espacos: 2,
      tipoItem: 'arma-corpo-a-corpo',
      descricao: 'Arma tática ágil de duas mãos, arremessável. Ao causar dano, 2 PE permitem agarrar como ação livre. Pode funcionar como arma de uma mão e leve para ataques adicionais. Item único.',
    }, 'as3', 112),
  ],
  armasPesadas: [
    comFonte({
      id: 'lancador_granadas',
      nome: 'Lançador de Granadas',
      categoria: 2,
      dano: 'Conforme a granada',
      critico: 'x2',
      alcance: 'Longo',
      tipo: 'Especial',
      espacos: 2,
      tipoItem: 'arma-fogo',
      tiposItem: ['arma', 'arma-fogo', 'arma-fogo-mira', 'lancador-granadas'],
      descricao: 'Arma de fogo pesada de duas mãos para até seis granadas 40 mm. Recarregar cada granada gasta uma ação de movimento. Pode mirar em um ser ou ponto em alcance longo.',
    }, 'as4', 71),
  ],
  equipGeral: [
    comFonte({
      id: 'rubra',
      nome: 'Rubra',
      categoria: 2,
      espacos: 1,
      descricao: 'Ação de movimento em uma ferida aberta: +5 em testes de Força, Agilidade e Vigor e 10 PV temporários na cena. Depois pode causar perda temporária de atributos físicos e exige Vontade contra insanidade.',
    }, 'as1', 54),
    comFonte({
      id: 'pacoca',
      nome: 'Paçoca',
      categoria: 0,
      espacos: 0.5,
      descricao: 'Conta como prato rápido. Em ocasião especial, uma vez por dia pode recuperar 1d8+1 PV, PE e SAN.',
    }, 'as3', 112),
    comFonte({
      id: 'bloody_mary_batizada',
      nome: 'Bloody Mary Batizada',
      categoria: 2,
      espacos: 1,
      descricao: 'Remove uma condição mental e/ou de medo, mas causa 2d4 de dano mental.',
    }, 'as3', 112),
    comFonte({
      id: 'granada_gas_lacrimogeneo',
      nome: 'Granada de Gás Lacrimogêneo',
      categoria: 1,
      espacos: 1,
      tipoItem: 'granada',
      descricao: 'Explosão em raio de 6m: 4d6 químico, enjoado e dificuldade de respirar. Fortitude DT Agi reduz o dano e evita enjoado.',
    }, 'as4', 70),
    comFonte({
      id: 'granada_tinta',
      nome: 'Granada de Tinta',
      categoria: 0,
      espacos: 1,
      tipoItem: 'granada',
      descricao: 'Explosão em raio de 6m: alvos ficam vulneráveis e sofrem -2d20 em Furtividade até o fim da cena. Reflexos DT Agi evita.',
    }, 'as4', 70),
  ],
  itensParanormais: [
    comFonte({ id: 'conector_membros', nome: 'Conector de Membros', elemento: 'Sangue', categoria: 3, espacos: 1, descricao: 'Ação padrão para reconectar membro ou cabeça decepados há até três rodadas. Pode remover morto ou morrendo e deixar o alvo inconsciente com 1 PV, mas há 25% de chance de o membro adquirir comportamento próprio.' }, 'sah', 58),
    comFonte({ id: 'dose_praga', nome: 'Dose d’A Praga', elemento: 'Sangue', categoria: 3, espacos: 1, descricao: 'Ação padrão: concede Arma de Sangue, Sangue de Ferro e Sangue Vivo na cena. Ao final, Fortitude crescente evita dano mental e prolongamento compulsório com Ódio Incontrolável.' }, 'sah', 58),
    comFonte({ id: 'mandibula_agonizante', nome: 'Mandíbula Agonizante', elemento: 'Sangue', categoria: 2, espacos: 1, descricao: 'Ação padrão e arremesso em alcance médio: abafa outros sons em 30m até o fim da cena, garante distração em furtividade e atrai criaturas de Sangue. Recarrega após descanso.' }, 'sah', 58),
    comFonte({ id: 'retalho_tenebroso', nome: 'Retalho Tenebroso', elemento: 'Sangue', categoria: 2, espacos: 1, descricao: 'Máscara que concede faro e visão no escuro, mas vulnerabilidade a Morte e -2d20 em interações sociais. Acumula dano extra por dia e tenta consumir a carne do usuário.' }, 'sah', 59),
    comFonte({ id: 'ampulheta_tempo_sofrido', nome: 'Ampulheta do Tempo Sofrido', elemento: 'Morte', categoria: 2, espacos: 1, descricao: 'Empunhada, permite gastar 5 PE para receber imediatamente o benefício de uma ação de interlúdio. Só volta a funcionar após gastar uma ação de interlúdio devolvendo o tempo.' }, 'sah', 59),
    comFonte({ id: 'injecao_lodo', nome: 'Injeção de Lodo', elemento: 'Morte', categoria: 2, espacos: 0.5, descricao: 'Consumível: concede vulnerabilidade a dano balístico e Energia; na próxima vez que chegaria a 0 PV na cena, fica com 1 PV.' }, 'sah', 60),
    comFonte({ id: 'instantaneo_mortal', nome: 'Instantâneo Mortal', elemento: 'Morte', categoria: 2, espacos: 0.5, descricao: 'Empunhado, 1 PE concede +1d20 em um teste para procurar pistas quando a perícia se relacionar às circunstâncias da morte retratada.' }, 'sah', 60),
    comFonte({ id: 'projetil_lodo_curto', nome: 'Projétil de Lodo (curto)', elemento: 'Morte', categoria: 1, espacos: 1, descricao: 'Munição curta que transforma todo dano da arma em Morte; ao fim da cena, a arma é consumida pelo tempo.' }, 'sah', 60),
    comFonte({ id: 'projetil_lodo_longo', nome: 'Projétil de Lodo (longo)', elemento: 'Morte', categoria: 2, espacos: 1, descricao: 'Munição longa que transforma todo dano da arma em Morte; ao fim da cena, a arma é consumida pelo tempo.' }, 'sah', 60),
    comFonte({ id: 'radio_chiador', nome: 'Rádio Chiador', elemento: 'Morte', categoria: 2, espacos: 1, descricao: 'Detecta criaturas paranormais em alcance extremo por chiados que indicam direção e distância aproximadas; também pode atraí-las.' }, 'sah', 60),
    comFonte({ id: 'camera_obscura', nome: 'Câmera Obscura', elemento: 'Conhecimento', categoria: 3, espacos: 1, descricao: 'Câmera de aura com lente de revelação, DT +10 e 6d6 de frio contra criaturas invisíveis, incorpóreas ou camufladas que falharem.' }, 'sah', 60),
    comFonte({ id: 'enxame_fantasmagorico', nome: 'Enxame Fantasmagórico', elemento: 'Conhecimento', categoria: 3, espacos: 1, descricao: 'Manto que deixa o usuário invisível, mas causa 1 dano mental irredutível no início de cada turno.' }, 'sah', 61),
    comFonte({ id: 'repositorio_fracasso', nome: 'Repositório do Fracasso', elemento: 'Conhecimento', categoria: 2, espacos: 1, descricao: 'Acumula até seis cargas com resultados 1 de criaturas paranormais próximas. Uma vez por rodada, gaste uma carga para recuperar 1d4 PE e sofrer -1 cumulativo em Vontade até o interlúdio.' }, 'sah', 61),
    comFonte({ id: 'tabula_saber_custoso', nome: 'Tábula do Saber Custoso', elemento: 'Conhecimento', categoria: 2, espacos: 1, descricao: 'Empunhada, permite ser considerado treinado em uma perícia por um teste, perdendo SAN igual ao atributo-chave usado.' }, 'sah', 61),
    comFonte({ id: 'arreio_neural', nome: 'Arreio Neural', elemento: 'Energia', categoria: 2, espacos: 1, descricao: 'Ao sofrer pelo menos 5 de eletricidade ou Energia, recupera 1 PE, até o dobro do Vigor por dia.' }, 'sah', 61),
    comFonte({ id: 'centrifugador_existencial', nome: 'Centrifugador Existencial', elemento: 'Energia', categoria: 3, espacos: 1, descricao: 'Ação padrão e 3 PE concedem um turno adicional no fim da rodada, mas um teste crescente de Ocultismo evita perder temporariamente metade dos atributos.' }, 'sah', 61),
    comFonte({ id: 'espelho_refletor', nome: 'Espelho Refletor', elemento: 'Energia', categoria: 2, espacos: 1, descricao: 'Permite observar ângulos impossíveis em alcance médio com +1d20 em Percepção. Pode ser sacrificado para evitar dano de Energia e refleti-lo à fonte.' }, 'sah', 62),
    comFonte({ id: 'fuzil_alheio', nome: 'Fuzil Alheio', elemento: 'Energia', categoria: 4, espacos: 2, dano: '2d10', critico: '17/x3', alcance: 'Extremo', tipo: 'Energia', tipoItem: 'arma-fogo', descricao: 'Fuzil de precisão com mira telescópica e laser. Causa Energia e não usa munição.' }, 'sah', 62),
    comFonte({ id: 'primeira_adaga', nome: 'A Primeira Adaga', elemento: 'Medo', categoria: 3, espacos: 1, dano: '1d4', critico: 'x3', alcance: '-', tipo: 'P', tipoItem: 'arma-corpo-a-corpo', descricao: 'Como componente, concede os quatro catalisadores e muda a conjuração para uma rodada, mas custa metade dos PV totais do conjurador, contando para dano massivo.' }, 'sah', 62),
    comFonte({ id: 'amuleto_sinalizador_elemento', nome: 'Amuleto Sinalizador de Elemento', elemento: 'Variável', categoria: 2, espacos: 1, descricao: 'Escolha Sangue, Morte, Conhecimento ou Energia. O amuleto sinaliza quando uma criatura do elemento entra em alcance longo, mesmo através de obstáculos.' }, 'as1', 54),
    comFonte({ id: 'agrupador_ritualistico', nome: 'Agrupador Ritualístico', elemento: 'Variável', categoria: 2, espacos: 1, descricao: 'Ação padrão prende até quatro componentes ou catalisadores. Enquanto empunhado, todos os itens presos contam como empunhados.' }, 'as1', 54),
    comFonte({ id: 'arpao_pescador', nome: 'Arpão do Pescador', elemento: 'Sangue', categoria: 3, espacos: 1, dano: '1d8 + 1d12 Sangue', critico: '20/x3', alcance: 'Curto', tipo: 'P', tipoItem: 'arma-corpo-a-corpo', descricao: 'Arma simples arremessável. Ao acertar à distância, deixa o alvo lento até ele remover o arpão com ação padrão e Atletismo DT For.' }, 'as1', 55),
    comFonte({ id: 'combustivel_sangue', nome: 'Combustível de Sangue', elemento: 'Sangue', categoria: 3, espacos: 1, descricao: 'Munição de lança-chamas ou galão. Converte todo o dano para Sangue e aumenta cada dado em um passo.' }, 'as1', 55),
    comFonte({ id: 'marreta_transtornada', nome: 'Marreta Transtornada', elemento: 'Sangue', categoria: 4, espacos: 2, dano: '2d10 + 2d12 Sangue', critico: '20/x4', alcance: '-', tipo: 'I', tipoItem: 'arma-corpo-a-corpo', descricao: 'Perde 1d6 PV ao empunhar ou atacar. Em crítico, Fortitude DT For evita osso quebrado: fraco até cuidados prolongados, ou debilitado se já estiver fraco.' }, 'as1', 55),
    comFonte({ id: 'cranio_dominador', nome: 'Crânio Dominador', elemento: 'Morte', categoria: 3, espacos: 1, descricao: 'Empunhado, ação padrão e 2 PE invocam correntes contra até dois alvos em alcance curto. Reflexos DT Pre evita; correntes têm Defesa 10, RD 10 e 20 PV. Recarrega em 24 horas.' }, 'as3', 113),
    comFonte({ id: 'gaiola_corvo', nome: 'Gaiola do Corvo', elemento: 'Morte', categoria: 3, espacos: 2, descricao: 'Cria Lodo em raio de 18m, terreno difícil que causa 3d10 Morte por rodada. Um ser que fique morrendo é consumido e encerra o efeito.' }, 'as3', 113),
    comFonte({ id: 'camiseta_psikolera', nome: 'Camiseta PSIKOLERA', elemento: 'Sangue', categoria: 2, espacos: 1, descricao: 'Enquanto machucado, todas as rolagens de dano causam +2d8 Sangue.' }, 'as3', 114),
    comFonte({ id: 'dupla_obsessiva', nome: 'Dupla Obsessiva', elemento: 'Sangue', categoria: 3, espacos: 2, dano: 'Maça 2d4+1d6 Sangue; florete 1d6+2d4 Sangue', critico: 'Maça 20/x3; florete 18/x2', alcance: '-', tipo: 'P', tipoItem: 'arma-corpo-a-corpo', descricao: 'Conjunto de maça e florete. Permite dois ataques e pode redirecionar para você ataques contra aliados em alcance curto, com contra-ataque possível.' }, 'as3', 114),
    comFonte({ id: 'armadura_couracas', nome: 'Armadura dos Couraças', elemento: 'Sangue', categoria: 3, espacos: 0, defesa: 10, tipoItem: 'protecao-pesada', descricao: 'Proteção pesada orgânica: Defesa +10 crescente com uso, RD balístico/impacto/perfuração 5 e Sangue 10, sem peso ou penalidade e sem exigir proficiência. Causa vulnerabilidade a Morte e pode controlar o usuário.' }, 'as3', 115),
    comFonte({ id: 'granada_ctrl_c_ctrl_v', nome: 'Granada Ctrl+C Ctrl+V', elemento: 'Energia', categoria: 2, espacos: 1, tipoItem: 'granada', descricao: 'Explosão de 8d6 Energia em raio de 6m, Reflexos DT Agi reduz à metade. Em resultado par de 1d4, replica a explosão em outro ponto, até quatro explosões.' }, 'as4', 70),
  ],
  modificacoesGranadas: [
    comFonte({ key: 'granada_adesiva', nome: 'Adesiva', tipo: ['granada'], cat: 1, descricao: 'A granada gruda no alvo. Se o ataque acertar, ele falha automaticamente na resistência; efeitos persistentes se movem com o alvo até remoção por ação padrão.' }, 'as4', 71),
    comFonte({ key: 'granada_dupla', nome: 'Dupla', tipo: ['granada'], cat: 1, descricao: 'A granada recebe o efeito adicional de outra granada não amaldiçoada, diferente do efeito principal.' }, 'as4', 71),
    comFonte({ key: 'granada_programada', nome: 'Programada', tipo: ['granada'], cat: 1, descricao: 'Permite definir, ao arremessar ou posicionar, em quantos turnos a granada explodirá.' }, 'as4', 71),
  ],
};

const OPTIONAL_RULES = [
  comFonte({ id: 'sah-investigacao', titulo: 'Investigação expandida', categoria: 'Cena', status: 'integrada', resumo: 'Novas ações, urgência e eventos de investigação. O sistema já registra ações de interlúdio e efeitos relacionados; a referência reúne as opções para uso do mestre.' }, 'sah', 82),
  comFonte({ id: 'sah-medo', titulo: 'Medo em jogo', categoria: 'Terror', status: 'referencia', resumo: 'Orienta entregar-se ou resistir ao medo e lidar com seus efeitos narrativos e mecânicos.' }, 'sah', 88),
  comFonte({ id: 'sah-perseguicoes', titulo: 'Perseguições', categoria: 'Cena', status: 'integrada', resumo: 'Usa sucessos, falhas e ações de fuga. A ficha e o painel do mestre já acompanham metas e progresso por personagem.' }, 'sah', 91),
  comFonte({ id: 'sah-furtividade', titulo: 'Furtividade por visibilidade', categoria: 'Cena', status: 'integrada', resumo: 'Controla o quanto cada personagem está exposto durante uma cena de furtividade. A ficha já possui o marcador de visibilidade.' }, 'sah', 93),
  comFonte({ id: 'sah-fabricacao', titulo: 'Fabricação em campo', categoria: 'Equipamento', status: 'referencia', resumo: 'Permite fabricar, reparar e modificar equipamentos usando ações de manutenção e testes de Profissão.' }, 'sah', 95),
  comFonte({ id: 'sah-vida-ordem', titulo: 'Vida além da Ordem', categoria: 'Campanha', status: 'referencia', resumo: 'Estrutura folgas, relações e projetos entre missões sem transformá-los em conteúdo fixo de campanha.' }, 'sah', 95),
  comFonte({ id: 'sah-nex-experiencia', titulo: 'NEX e experiência separados', categoria: 'Progressão', status: 'opcional', resumo: 'Separa capacidade do agente de exposição paranormal. Deve ser ativada conscientemente pela mesa.' }, 'sah', 99),
  comFonte({ id: 'sah-sem-sanidade', titulo: 'Jogando sem Sanidade', categoria: 'Terror', status: 'opcional', resumo: 'Substitui SAN por determinação para mesas que desejem outro ritmo de horror.' }, 'sah', 105),
  comFonte({ id: 'sah-ferimentos', titulo: 'Ferimentos debilitantes', categoria: 'Condição', status: 'opcional', resumo: 'Transforma danos graves em sequelas persistentes. Não é aplicado automaticamente às fichas.' }, 'sah', 106),
  comFonte({ id: 'sah-sem-mapa', titulo: 'Jogando sem mapa', categoria: 'Cena', status: 'opcional', resumo: 'Converte distâncias e posicionamento em zonas narrativas para mesas sem tabuleiro.' }, 'sah', 107),
  comFonte({ id: 'sah-patentes', titulo: 'Evolução por patentes', categoria: 'Progressão', status: 'opcional', resumo: 'Usa patente como eixo principal de evolução e acesso a equipamentos.' }, 'sah', 109),
  comFonte({ id: 'sah-compreensao', titulo: 'Limites da compreensão humana', categoria: 'Ritual', status: 'opcional', resumo: 'Reformula aprendizado e acesso a rituais para torná-los mais raros e perigosos.' }, 'sah', 114),
  comFonte({ id: 'sah-conjuracao-complexa', titulo: 'Conjuração complexa', categoria: 'Ritual', status: 'opcional', resumo: 'Divide a conjuração em etapas e permite preparação antecipada. Não altera automaticamente rituais existentes.' }, 'sah', 115),
  comFonte({ id: 'sah-rituais-desconhecidos', titulo: 'Conjurar rituais desconhecidos', categoria: 'Ritual', status: 'opcional', resumo: 'Permite tentar fontes e símbolos ainda não dominados, com riscos definidos pelo módulo.' }, 'sah', 118),
  comFonte({ id: 'sah-combate-narrativo', titulo: 'Combate narrativo', categoria: 'Cena', status: 'opcional', resumo: 'Substitui parte do combate tático por resolução narrativa e abstrata.' }, 'sah', 120),
  comFonte({ id: 'as1-blindar-mente', titulo: 'Blindar a Mente', categoria: 'Uso de perícia', status: 'referencia', resumo: 'Ocultismo veterano, ação completa e 1 PE. Em DT 20 concede +5 no próximo teste de Vontade da cena; também pode proteger aliado com DTs maiores e risco mental.' }, 'as1', 43),
  comFonte({ id: 'as1-transcender-itens', titulo: 'Transcender com itens amaldiçoados', categoria: 'Progressão', status: 'opcional', resumo: 'Consome um item amaldiçoado em uma experiência narrativa para obter um poder paranormal do mesmo elemento, respeitando pré-requisitos e limites por faixa de NEX.' }, 'as1', 56),
  comFonte({ id: 'as1-reter-ritual', titulo: 'Reter Ritual', categoria: 'Ritual', status: 'opcional', resumo: 'Troca duração cena por retida, reduzindo PE atuais e máximos enquanto o efeito permanece e cobrando 1 SAN. Encerrar com calma exige ação padrão e Ocultismo.' }, 'as1', 58),
  comFonte({ id: 'as2-poderes-intencao', titulo: 'Poderes de Intenção', categoria: 'Paranormal', status: 'opcional', resumo: 'Cada poder exige contato com a Coroa de Espinhos e um gatilho narrativo. Após o uso, o gatilho precisa ser cumprido novamente.' }, 'as2', 94),
  comFonte({ id: 'as2-mascaras', titulo: 'Máscaras e forma suprema', categoria: 'Transformação', status: 'opcional', resumo: 'Ativar custa ação de movimento e 6 SAN, mais 2 SAN por rodada adicional. Concede +20 PV máximos/atuais, +10 PE máximos/atuais e +10 Defesa, além de uma ficha de forma acordada com o mestre.' }, 'as2', 97),
  comFonte({ id: 'as3-batalha-intencoes', titulo: 'Batalha de Intenções', categoria: 'Cena', status: 'opcional', resumo: 'Duelo entre duas pessoas: contra o rival causa +1d10 do mesmo tipo; contra qualquer outra fonte reduz dano pela metade.' }, 'as3', 120),
  comFonte({ id: 'as3-troca-recursos', titulo: 'Trocas de recursos', categoria: 'Campanha', status: 'opcional', resumo: 'Informações custam 1 recurso e segredos custam 3 recursos, com tipo de recurso definido pelo NPC ou pela situação.' }, 'as3', 121),
  comFonte({ id: 'as3-construcao-base', titulo: 'Construção de base', categoria: 'Campanha', status: 'opcional', resumo: 'Uma melhoria complexa leva sete dias com uma pessoa; cada pessoa adicional reduz um dia, até o mínimo de três.' }, 'as3', 121),
  comFonte({ id: 'as3-paixao', titulo: 'Regras da Paixão', categoria: 'Relação', status: 'opcional', resumo: 'Com consentimento explícito da mesa, personagens apaixonados podem receber recursos adicionais e consequências pela perda. Inclui as condições Apaixonado e Trêmulo.' }, 'as3', 124),
  comFonte({ id: 'as3-veiculos', titulo: 'Veículos operacionais', categoria: 'Veículo', status: 'opcional', resumo: 'Define categorias, PV, Defesa, RD, carga, regalias, combustível, direção combativa, dano massivo e reparo de veículos.' }, 'as3', 125),
  comFonte({ id: 'as3-animais', titulo: 'Animais treinados', categoria: 'Aliado', status: 'opcional', resumo: 'Permite usar o animal como aliado ou ficha de ameaça da realidade, com treinamento durante folga e evolução de VD ligada ao NEX.' }, 'as3', 132),
  comFonte({ id: 'as4-obter-informacoes', titulo: 'Obter Informações', categoria: 'Uso de perícia', status: 'referencia', resumo: 'Tecnologia DT 5 e ação completa para pesquisa rápida. Obtém uma informação e mais uma para cada 5 pontos acima da DT.' }, 'as4', 64),
  comFonte({ id: 'as4-hacking', titulo: 'Cena de Hacking', categoria: 'Cena', status: 'opcional', resumo: 'Transforma a segurança em PS e usa dados virtuais para procurar brechas, quebrar códigos, cobrir rastros, criar backdoors e plantar vírus, com imprevistos no fim das rodadas.' }, 'as4', 72),
];

export {
  OPTIONAL_RULES,
  SUPPLEMENT_BOOKS,
  SUPPLEMENT_ITEMS,
  SUPPLEMENT_ORIGINS,
  SUPPLEMENT_POWERS,
  SUPPLEMENT_RITUALS,
  SUPPLEMENT_TRAILS,
};
